/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "MockSetContactorsTask.h"

static const char* CMockString_arg = "arg";
static const char* CMockString_disconnectContactors = "disconnectContactors";
static const char* CMockString_isContactorError = "isContactorError";
static const char* CMockString_setContactorsTask = "setContactorsTask";

typedef struct _CMOCK_setContactorsTask_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    void const* Expected_arg;

} CMOCK_setContactorsTask_CALL_INSTANCE;

typedef struct _CMOCK_disconnectContactors_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    uint8_t Expected_isContactorError;

} CMOCK_disconnectContactors_CALL_INSTANCE;

static struct MockSetContactorsTaskInstance
{
    CMOCK_MEM_INDEX_TYPE setContactorsTask_CallInstance;
    CMOCK_MEM_INDEX_TYPE disconnectContactors_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockSetContactorsTask_Verify(void)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_MEM_INDEX_TYPE call_instance;
    call_instance = Mock.setContactorsTask_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_setContactorsTask);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.disconnectContactors_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_disconnectContactors);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }
}

void MockSetContactorsTask_Init(void)
{
    MockSetContactorsTask_Destroy();
}

void MockSetContactorsTask_Destroy(void)
{
    CMock_Guts_MemFreeAll();
    memset(&Mock, 0, sizeof(Mock));
}

void setContactorsTask(void const* arg)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_setContactorsTask_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_setContactorsTask);
    cmock_call_instance = (CMOCK_setContactorsTask_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.setContactorsTask_CallInstance);
    Mock.setContactorsTask_CallInstance = CMock_Guts_MemNext(Mock.setContactorsTask_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_setContactorsTask, CMockString_arg);

        if (cmock_call_instance->Expected_arg == NULL)
        {
            UNITY_TEST_ASSERT_NULL(arg, cmock_line, CMockStringExpNULL);
        }
        else
        {
            UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_arg, arg, 1, cmock_line, CMockStringMismatch);
        }
    }
    UNITY_CLR_DETAILS();
}

void CMockExpectParameters_setContactorsTask(CMOCK_setContactorsTask_CALL_INSTANCE* cmock_call_instance, void const* arg)
{
    cmock_call_instance->Expected_arg = arg;
}

void setContactorsTask_CMockExpect(UNITY_LINE_TYPE cmock_line, void const* arg)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_setContactorsTask_CALL_INSTANCE));
    CMOCK_setContactorsTask_CALL_INSTANCE* cmock_call_instance = (CMOCK_setContactorsTask_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.setContactorsTask_CallInstance = CMock_Guts_MemChain(Mock.setContactorsTask_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_setContactorsTask(cmock_call_instance, arg);
}

void disconnectContactors(uint8_t isContactorError)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_disconnectContactors_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_disconnectContactors);
    cmock_call_instance = (CMOCK_disconnectContactors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.disconnectContactors_CallInstance);
    Mock.disconnectContactors_CallInstance = CMock_Guts_MemNext(Mock.disconnectContactors_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_disconnectContactors, CMockString_isContactorError);
        UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_isContactorError, isContactorError, cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
}

void CMockExpectParameters_disconnectContactors(CMOCK_disconnectContactors_CALL_INSTANCE* cmock_call_instance, uint8_t isContactorError)
{
    cmock_call_instance->Expected_isContactorError = isContactorError;
}

void disconnectContactors_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t isContactorError)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_disconnectContactors_CALL_INSTANCE));
    CMOCK_disconnectContactors_CALL_INSTANCE* cmock_call_instance = (CMOCK_disconnectContactors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.disconnectContactors_CallInstance = CMock_Guts_MemChain(Mock.disconnectContactors_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_disconnectContactors(cmock_call_instance, isContactorError);
}

