sudo: required

install:
    - wget 'https://sourceforge.net/projects/astyle/files/latest/download'
    - tar -zxvf download
    - (cd astyle/build/gcc && make release && sudo make install)
    - rm astyle -rf

script: 
    - "! (astyle *.h *.c -r --dry-run --options=astylerc | grep Formatted)"

language: c
