addons:
    apt:
        packages:
            - libc6:i386
            - libncurses5:i386
            - libstdc++6:i386
before_install:
    - git clone https://github.com/UCSolarCarTeam/Recruit-Resources.git
install:
    - (cd Recruit-Resources/STM32F4Discovery-Resources && sudo ./install.sh)
    - rm Recruit-Resources -rf
    - wget 'https://s3-us-west-2.amazonaws.com/ucsolarteam.hostedfiles/astyle'
    - tar -zxvf astyle
    - (cd astyle/build/gcc && make release && sudo make install)
    - rm astyle -rf

before_script:
    - source ~/.profile
    - (cd EpsilonLights && CubeMX2Makefile .)
    - (cd EpsilonDriverControls && CubeMX2Makefile .)
    - (cd EpsilonCCS && CubeMX2Makefile .)

script: 
    - (cd EpsilonLights && make)
    - (cd EpsilonDriverControls && make)
    - (cd EpsilonCCS && make)
    - "! (astyle *.h *.c -r --dry-run --options=astylerc | grep Formatted)"

language: c
