#pragma once

typedef enum
{
    MALLOC_FAILED,
    STACK_OVERFLOW,
    STACK_OVERFLOW_STARTUP_TASK,
    STACK_OVERFLOW_CAN_RX_PARSER_TASK,
    STACK_OVERFLOW_ORION_INTERFACE_TASK,
    STACK_OVERFLOW_CAN_TX_GTKPR_TASK,
    STACK_OVERFLOW_SEND_AUX_STATUS_TASK,
    STACK_OVERFLOW_SEND_AUX_TRIP_TASK,
    STACK_OVERFLOW_SEND_HEARTBEAT_TASK,
    STACK_OVERFLOW_COMMON_CONTACTOR_GATEKEEPER_TASK,
    STACK_OVERFLOW_CHARGE_CONTACTOR_GATEKEEPER_TASK,
    STACK_OVERFLOW_DISCHARGE_CONTACTOR_GATEKEEPER_TASK,
    STACK_OVERFLOW_CONTACTOR_STATUS_UPDATE_TASK,
    STACK_OVERFLOW_READ_AUX_VOLTAGE_TASK,
    SETUP
} ErrorCodes;
