/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "MockTrip.h"

static const char* CMockString_chargeShouldTrip = "chargeShouldTrip";
static const char* CMockString_dischargeShouldTrip = "dischargeShouldTrip";

typedef struct _CMOCK_chargeShouldTrip_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    int ReturnVal;

} CMOCK_chargeShouldTrip_CALL_INSTANCE;

typedef struct _CMOCK_dischargeShouldTrip_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    int ReturnVal;

} CMOCK_dischargeShouldTrip_CALL_INSTANCE;

static struct MockTripInstance
{
    CMOCK_MEM_INDEX_TYPE chargeShouldTrip_CallInstance;
    CMOCK_MEM_INDEX_TYPE dischargeShouldTrip_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockTrip_Verify(void)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_MEM_INDEX_TYPE call_instance;
    call_instance = Mock.chargeShouldTrip_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_chargeShouldTrip);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.dischargeShouldTrip_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_dischargeShouldTrip);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }
}

void MockTrip_Init(void)
{
    MockTrip_Destroy();
}

void MockTrip_Destroy(void)
{
    CMock_Guts_MemFreeAll();
    memset(&Mock, 0, sizeof(Mock));
}

int chargeShouldTrip(void)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_chargeShouldTrip_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_chargeShouldTrip);
    cmock_call_instance = (CMOCK_chargeShouldTrip_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.chargeShouldTrip_CallInstance);
    Mock.chargeShouldTrip_CallInstance = CMock_Guts_MemNext(Mock.chargeShouldTrip_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void chargeShouldTrip_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_chargeShouldTrip_CALL_INSTANCE));
    CMOCK_chargeShouldTrip_CALL_INSTANCE* cmock_call_instance = (CMOCK_chargeShouldTrip_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.chargeShouldTrip_CallInstance = CMock_Guts_MemChain(Mock.chargeShouldTrip_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    cmock_call_instance->ReturnVal = cmock_to_return;
}

int dischargeShouldTrip(void)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_dischargeShouldTrip_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_dischargeShouldTrip);
    cmock_call_instance = (CMOCK_dischargeShouldTrip_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dischargeShouldTrip_CallInstance);
    Mock.dischargeShouldTrip_CallInstance = CMock_Guts_MemNext(Mock.dischargeShouldTrip_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void dischargeShouldTrip_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dischargeShouldTrip_CALL_INSTANCE));
    CMOCK_dischargeShouldTrip_CALL_INSTANCE* cmock_call_instance = (CMOCK_dischargeShouldTrip_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.dischargeShouldTrip_CallInstance = CMock_Guts_MemChain(Mock.dischargeShouldTrip_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    cmock_call_instance->ReturnVal = cmock_to_return;
}

