/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockstm32f4xx_hal_gpio.h"

static const char* CMockString_GPIO_Init = "GPIO_Init";
static const char* CMockString_GPIO_Pin = "GPIO_Pin";
static const char* CMockString_GPIOx = "GPIOx";
static const char* CMockString_HAL_GPIO_DeInit = "HAL_GPIO_DeInit";
static const char* CMockString_HAL_GPIO_EXTI_Callback = "HAL_GPIO_EXTI_Callback";
static const char* CMockString_HAL_GPIO_EXTI_IRQHandler = "HAL_GPIO_EXTI_IRQHandler";
static const char* CMockString_HAL_GPIO_Init = "HAL_GPIO_Init";
static const char* CMockString_HAL_GPIO_LockPin = "HAL_GPIO_LockPin";
static const char* CMockString_HAL_GPIO_ReadPin = "HAL_GPIO_ReadPin";
static const char* CMockString_HAL_GPIO_TogglePin = "HAL_GPIO_TogglePin";
static const char* CMockString_HAL_GPIO_WritePin = "HAL_GPIO_WritePin";
static const char* CMockString_PinState = "PinState";

typedef struct _CMOCK_HAL_GPIO_Init_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    GPIO_TypeDef* Expected_GPIOx;
    GPIO_InitTypeDef* Expected_GPIO_Init;

} CMOCK_HAL_GPIO_Init_CALL_INSTANCE;

typedef struct _CMOCK_HAL_GPIO_DeInit_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    GPIO_TypeDef* Expected_GPIOx;
    uint32_t Expected_GPIO_Pin;

} CMOCK_HAL_GPIO_DeInit_CALL_INSTANCE;

typedef struct _CMOCK_HAL_GPIO_ReadPin_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    GPIO_PinState ReturnVal;
    GPIO_TypeDef* Expected_GPIOx;
    uint16_t Expected_GPIO_Pin;

} CMOCK_HAL_GPIO_ReadPin_CALL_INSTANCE;

typedef struct _CMOCK_HAL_GPIO_WritePin_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    GPIO_TypeDef* Expected_GPIOx;
    uint16_t Expected_GPIO_Pin;
    GPIO_PinState Expected_PinState;

} CMOCK_HAL_GPIO_WritePin_CALL_INSTANCE;

typedef struct _CMOCK_HAL_GPIO_TogglePin_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    GPIO_TypeDef* Expected_GPIOx;
    uint16_t Expected_GPIO_Pin;

} CMOCK_HAL_GPIO_TogglePin_CALL_INSTANCE;

typedef struct _CMOCK_HAL_GPIO_LockPin_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    HAL_StatusTypeDef ReturnVal;
    GPIO_TypeDef* Expected_GPIOx;
    uint16_t Expected_GPIO_Pin;

} CMOCK_HAL_GPIO_LockPin_CALL_INSTANCE;

typedef struct _CMOCK_HAL_GPIO_EXTI_IRQHandler_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    uint16_t Expected_GPIO_Pin;

} CMOCK_HAL_GPIO_EXTI_IRQHandler_CALL_INSTANCE;

typedef struct _CMOCK_HAL_GPIO_EXTI_Callback_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    uint16_t Expected_GPIO_Pin;

} CMOCK_HAL_GPIO_EXTI_Callback_CALL_INSTANCE;

static struct Mockstm32f4xx_hal_gpioInstance
{
    CMOCK_MEM_INDEX_TYPE HAL_GPIO_Init_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_GPIO_DeInit_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_GPIO_ReadPin_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_GPIO_WritePin_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_GPIO_TogglePin_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_GPIO_LockPin_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_GPIO_EXTI_IRQHandler_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_GPIO_EXTI_Callback_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockstm32f4xx_hal_gpio_Verify(void)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_MEM_INDEX_TYPE call_instance;
    call_instance = Mock.HAL_GPIO_Init_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_GPIO_Init);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_GPIO_DeInit_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_GPIO_DeInit);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_GPIO_ReadPin_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_GPIO_ReadPin);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_GPIO_WritePin_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_GPIO_WritePin);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_GPIO_TogglePin_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_GPIO_TogglePin);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_GPIO_LockPin_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_GPIO_LockPin);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_GPIO_EXTI_IRQHandler_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_GPIO_EXTI_IRQHandler);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_GPIO_EXTI_Callback_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_GPIO_EXTI_Callback);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }
}

void Mockstm32f4xx_hal_gpio_Init(void)
{
    Mockstm32f4xx_hal_gpio_Destroy();
}

void Mockstm32f4xx_hal_gpio_Destroy(void)
{
    CMock_Guts_MemFreeAll();
    memset(&Mock, 0, sizeof(Mock));
}

void HAL_GPIO_Init(GPIO_TypeDef* GPIOx, GPIO_InitTypeDef* GPIO_Init)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_GPIO_Init_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_GPIO_Init);
    cmock_call_instance = (CMOCK_HAL_GPIO_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_GPIO_Init_CallInstance);
    Mock.HAL_GPIO_Init_CallInstance = CMock_Guts_MemNext(Mock.HAL_GPIO_Init_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_GPIO_Init, CMockString_GPIOx);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_GPIOx), (void*)(GPIOx), sizeof(GPIO_TypeDef), cmock_line, CMockStringMismatch);
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_GPIO_Init, CMockString_GPIO_Init);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_GPIO_Init), (void*)(GPIO_Init), sizeof(GPIO_InitTypeDef), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_GPIO_Init(CMOCK_HAL_GPIO_Init_CALL_INSTANCE* cmock_call_instance, GPIO_TypeDef* GPIOx, GPIO_InitTypeDef* GPIO_Init)
{
    cmock_call_instance->Expected_GPIOx = GPIOx;
    cmock_call_instance->Expected_GPIO_Init = GPIO_Init;
}

void HAL_GPIO_Init_CMockExpect(UNITY_LINE_TYPE cmock_line, GPIO_TypeDef* GPIOx, GPIO_InitTypeDef* GPIO_Init)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_GPIO_Init_CALL_INSTANCE));
    CMOCK_HAL_GPIO_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_GPIO_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_GPIO_Init_CallInstance = CMock_Guts_MemChain(Mock.HAL_GPIO_Init_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_GPIO_Init(cmock_call_instance, GPIOx, GPIO_Init);
}

void HAL_GPIO_DeInit(GPIO_TypeDef* GPIOx, uint32_t GPIO_Pin)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_GPIO_DeInit_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_GPIO_DeInit);
    cmock_call_instance = (CMOCK_HAL_GPIO_DeInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_GPIO_DeInit_CallInstance);
    Mock.HAL_GPIO_DeInit_CallInstance = CMock_Guts_MemNext(Mock.HAL_GPIO_DeInit_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_GPIO_DeInit, CMockString_GPIOx);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_GPIOx), (void*)(GPIOx), sizeof(GPIO_TypeDef), cmock_line, CMockStringMismatch);
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_GPIO_DeInit, CMockString_GPIO_Pin);
        UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_GPIO_Pin, GPIO_Pin, cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_GPIO_DeInit(CMOCK_HAL_GPIO_DeInit_CALL_INSTANCE* cmock_call_instance, GPIO_TypeDef* GPIOx, uint32_t GPIO_Pin)
{
    cmock_call_instance->Expected_GPIOx = GPIOx;
    cmock_call_instance->Expected_GPIO_Pin = GPIO_Pin;
}

void HAL_GPIO_DeInit_CMockExpect(UNITY_LINE_TYPE cmock_line, GPIO_TypeDef* GPIOx, uint32_t GPIO_Pin)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_GPIO_DeInit_CALL_INSTANCE));
    CMOCK_HAL_GPIO_DeInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_GPIO_DeInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_GPIO_DeInit_CallInstance = CMock_Guts_MemChain(Mock.HAL_GPIO_DeInit_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_GPIO_DeInit(cmock_call_instance, GPIOx, GPIO_Pin);
}

GPIO_PinState HAL_GPIO_ReadPin(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_GPIO_ReadPin_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_GPIO_ReadPin);
    cmock_call_instance = (CMOCK_HAL_GPIO_ReadPin_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_GPIO_ReadPin_CallInstance);
    Mock.HAL_GPIO_ReadPin_CallInstance = CMock_Guts_MemNext(Mock.HAL_GPIO_ReadPin_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_GPIO_ReadPin, CMockString_GPIOx);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_GPIOx), (void*)(GPIOx), sizeof(GPIO_TypeDef), cmock_line, CMockStringMismatch);
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_GPIO_ReadPin, CMockString_GPIO_Pin);
        UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_GPIO_Pin, GPIO_Pin, cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_GPIO_ReadPin(CMOCK_HAL_GPIO_ReadPin_CALL_INSTANCE* cmock_call_instance, GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin)
{
    cmock_call_instance->Expected_GPIOx = GPIOx;
    cmock_call_instance->Expected_GPIO_Pin = GPIO_Pin;
}

void HAL_GPIO_ReadPin_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, GPIO_PinState cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_GPIO_ReadPin_CALL_INSTANCE));
    CMOCK_HAL_GPIO_ReadPin_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_GPIO_ReadPin_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_GPIO_ReadPin_CallInstance = CMock_Guts_MemChain(Mock.HAL_GPIO_ReadPin_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_GPIO_ReadPin(cmock_call_instance, GPIOx, GPIO_Pin);
    memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
           sizeof(GPIO_PinState[sizeof(cmock_to_return) == sizeof(GPIO_PinState) ? 1 : -1])); /* add GPIO_PinState to :treat_as_array if this causes an error */
}

void HAL_GPIO_WritePin(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, GPIO_PinState PinState)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_GPIO_WritePin_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_GPIO_WritePin);
    cmock_call_instance = (CMOCK_HAL_GPIO_WritePin_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_GPIO_WritePin_CallInstance);
    Mock.HAL_GPIO_WritePin_CallInstance = CMock_Guts_MemNext(Mock.HAL_GPIO_WritePin_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_GPIO_WritePin, CMockString_GPIOx);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_GPIOx), (void*)(GPIOx), sizeof(GPIO_TypeDef), cmock_line, CMockStringMismatch);
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_GPIO_WritePin, CMockString_GPIO_Pin);
        UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_GPIO_Pin, GPIO_Pin, cmock_line, CMockStringMismatch);
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_GPIO_WritePin, CMockString_PinState);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_PinState), (void*)(&PinState), sizeof(GPIO_PinState), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_GPIO_WritePin(CMOCK_HAL_GPIO_WritePin_CALL_INSTANCE* cmock_call_instance, GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, GPIO_PinState PinState)
{
    cmock_call_instance->Expected_GPIOx = GPIOx;
    cmock_call_instance->Expected_GPIO_Pin = GPIO_Pin;
    memcpy((void*)(&cmock_call_instance->Expected_PinState), (void*)(&PinState),
           sizeof(GPIO_PinState[sizeof(PinState) == sizeof(GPIO_PinState) ? 1 : -1])); /* add GPIO_PinState to :treat_as_array if this causes an error */
}

void HAL_GPIO_WritePin_CMockExpect(UNITY_LINE_TYPE cmock_line, GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, GPIO_PinState PinState)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_GPIO_WritePin_CALL_INSTANCE));
    CMOCK_HAL_GPIO_WritePin_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_GPIO_WritePin_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_GPIO_WritePin_CallInstance = CMock_Guts_MemChain(Mock.HAL_GPIO_WritePin_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_GPIO_WritePin(cmock_call_instance, GPIOx, GPIO_Pin, PinState);
}

void HAL_GPIO_TogglePin(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_GPIO_TogglePin_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_GPIO_TogglePin);
    cmock_call_instance = (CMOCK_HAL_GPIO_TogglePin_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_GPIO_TogglePin_CallInstance);
    Mock.HAL_GPIO_TogglePin_CallInstance = CMock_Guts_MemNext(Mock.HAL_GPIO_TogglePin_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_GPIO_TogglePin, CMockString_GPIOx);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_GPIOx), (void*)(GPIOx), sizeof(GPIO_TypeDef), cmock_line, CMockStringMismatch);
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_GPIO_TogglePin, CMockString_GPIO_Pin);
        UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_GPIO_Pin, GPIO_Pin, cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_GPIO_TogglePin(CMOCK_HAL_GPIO_TogglePin_CALL_INSTANCE* cmock_call_instance, GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin)
{
    cmock_call_instance->Expected_GPIOx = GPIOx;
    cmock_call_instance->Expected_GPIO_Pin = GPIO_Pin;
}

void HAL_GPIO_TogglePin_CMockExpect(UNITY_LINE_TYPE cmock_line, GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_GPIO_TogglePin_CALL_INSTANCE));
    CMOCK_HAL_GPIO_TogglePin_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_GPIO_TogglePin_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_GPIO_TogglePin_CallInstance = CMock_Guts_MemChain(Mock.HAL_GPIO_TogglePin_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_GPIO_TogglePin(cmock_call_instance, GPIOx, GPIO_Pin);
}

HAL_StatusTypeDef HAL_GPIO_LockPin(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_GPIO_LockPin_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_GPIO_LockPin);
    cmock_call_instance = (CMOCK_HAL_GPIO_LockPin_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_GPIO_LockPin_CallInstance);
    Mock.HAL_GPIO_LockPin_CallInstance = CMock_Guts_MemNext(Mock.HAL_GPIO_LockPin_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_GPIO_LockPin, CMockString_GPIOx);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_GPIOx), (void*)(GPIOx), sizeof(GPIO_TypeDef), cmock_line, CMockStringMismatch);
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_GPIO_LockPin, CMockString_GPIO_Pin);
        UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_GPIO_Pin, GPIO_Pin, cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_GPIO_LockPin(CMOCK_HAL_GPIO_LockPin_CALL_INSTANCE* cmock_call_instance, GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin)
{
    cmock_call_instance->Expected_GPIOx = GPIOx;
    cmock_call_instance->Expected_GPIO_Pin = GPIO_Pin;
}

void HAL_GPIO_LockPin_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, HAL_StatusTypeDef cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_GPIO_LockPin_CALL_INSTANCE));
    CMOCK_HAL_GPIO_LockPin_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_GPIO_LockPin_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_GPIO_LockPin_CallInstance = CMock_Guts_MemChain(Mock.HAL_GPIO_LockPin_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_GPIO_LockPin(cmock_call_instance, GPIOx, GPIO_Pin);
    memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
           sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

void HAL_GPIO_EXTI_IRQHandler(uint16_t GPIO_Pin)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_GPIO_EXTI_IRQHandler_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_GPIO_EXTI_IRQHandler);
    cmock_call_instance = (CMOCK_HAL_GPIO_EXTI_IRQHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_GPIO_EXTI_IRQHandler_CallInstance);
    Mock.HAL_GPIO_EXTI_IRQHandler_CallInstance = CMock_Guts_MemNext(Mock.HAL_GPIO_EXTI_IRQHandler_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_GPIO_EXTI_IRQHandler, CMockString_GPIO_Pin);
        UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_GPIO_Pin, GPIO_Pin, cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_GPIO_EXTI_IRQHandler(CMOCK_HAL_GPIO_EXTI_IRQHandler_CALL_INSTANCE* cmock_call_instance, uint16_t GPIO_Pin)
{
    cmock_call_instance->Expected_GPIO_Pin = GPIO_Pin;
}

void HAL_GPIO_EXTI_IRQHandler_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t GPIO_Pin)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_GPIO_EXTI_IRQHandler_CALL_INSTANCE));
    CMOCK_HAL_GPIO_EXTI_IRQHandler_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_GPIO_EXTI_IRQHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_GPIO_EXTI_IRQHandler_CallInstance = CMock_Guts_MemChain(Mock.HAL_GPIO_EXTI_IRQHandler_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_GPIO_EXTI_IRQHandler(cmock_call_instance, GPIO_Pin);
}

void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_GPIO_EXTI_Callback_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_GPIO_EXTI_Callback);
    cmock_call_instance = (CMOCK_HAL_GPIO_EXTI_Callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_GPIO_EXTI_Callback_CallInstance);
    Mock.HAL_GPIO_EXTI_Callback_CallInstance = CMock_Guts_MemNext(Mock.HAL_GPIO_EXTI_Callback_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_GPIO_EXTI_Callback, CMockString_GPIO_Pin);
        UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_GPIO_Pin, GPIO_Pin, cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_GPIO_EXTI_Callback(CMOCK_HAL_GPIO_EXTI_Callback_CALL_INSTANCE* cmock_call_instance, uint16_t GPIO_Pin)
{
    cmock_call_instance->Expected_GPIO_Pin = GPIO_Pin;
}

void HAL_GPIO_EXTI_Callback_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t GPIO_Pin)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_GPIO_EXTI_Callback_CALL_INSTANCE));
    CMOCK_HAL_GPIO_EXTI_Callback_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_GPIO_EXTI_Callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_GPIO_EXTI_Callback_CallInstance = CMock_Guts_MemChain(Mock.HAL_GPIO_EXTI_Callback_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_GPIO_EXTI_Callback(cmock_call_instance, GPIO_Pin);
}

