/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKTRIP_H
#define _MOCKTRIP_H

#include "unity.h"
#include "Trip.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void MockTrip_Init(void);
void MockTrip_Destroy(void);
void MockTrip_Verify(void);




#define chargeShouldTrip_ExpectAndReturn(cmock_retval) chargeShouldTrip_CMockExpectAndReturn(__LINE__, cmock_retval)
void chargeShouldTrip_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define dischargeShouldTrip_ExpectAndReturn(cmock_retval) dischargeShouldTrip_CMockExpectAndReturn(__LINE__, cmock_retval)
void dischargeShouldTrip_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
