/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockstm32f4xx_hal_adc.h"

static const char* CMockString_AnalogWDGConfig = "AnalogWDGConfig";
static const char* CMockString_EventType = "EventType";
static const char* CMockString_HAL_ADC_AnalogWDGConfig = "HAL_ADC_AnalogWDGConfig";
static const char* CMockString_HAL_ADC_ConfigChannel = "HAL_ADC_ConfigChannel";
static const char* CMockString_HAL_ADC_ConvCpltCallback = "HAL_ADC_ConvCpltCallback";
static const char* CMockString_HAL_ADC_ConvHalfCpltCallback = "HAL_ADC_ConvHalfCpltCallback";
static const char* CMockString_HAL_ADC_DeInit = "HAL_ADC_DeInit";
static const char* CMockString_HAL_ADC_ErrorCallback = "HAL_ADC_ErrorCallback";
static const char* CMockString_HAL_ADC_GetError = "HAL_ADC_GetError";
static const char* CMockString_HAL_ADC_GetState = "HAL_ADC_GetState";
static const char* CMockString_HAL_ADC_GetValue = "HAL_ADC_GetValue";
static const char* CMockString_HAL_ADC_IRQHandler = "HAL_ADC_IRQHandler";
static const char* CMockString_HAL_ADC_Init = "HAL_ADC_Init";
static const char* CMockString_HAL_ADC_LevelOutOfWindowCallback = "HAL_ADC_LevelOutOfWindowCallback";
static const char* CMockString_HAL_ADC_MspDeInit = "HAL_ADC_MspDeInit";
static const char* CMockString_HAL_ADC_MspInit = "HAL_ADC_MspInit";
static const char* CMockString_HAL_ADC_PollForConversion = "HAL_ADC_PollForConversion";
static const char* CMockString_HAL_ADC_PollForEvent = "HAL_ADC_PollForEvent";
static const char* CMockString_HAL_ADC_Start = "HAL_ADC_Start";
static const char* CMockString_HAL_ADC_Start_DMA = "HAL_ADC_Start_DMA";
static const char* CMockString_HAL_ADC_Start_IT = "HAL_ADC_Start_IT";
static const char* CMockString_HAL_ADC_Stop = "HAL_ADC_Stop";
static const char* CMockString_HAL_ADC_Stop_DMA = "HAL_ADC_Stop_DMA";
static const char* CMockString_HAL_ADC_Stop_IT = "HAL_ADC_Stop_IT";
static const char* CMockString_Length = "Length";
static const char* CMockString_Timeout = "Timeout";
static const char* CMockString_hadc = "hadc";
static const char* CMockString_pData = "pData";
static const char* CMockString_sConfig = "sConfig";

typedef struct _CMOCK_HAL_ADC_Init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  ADC_HandleTypeDef* Expected_hadc;

} CMOCK_HAL_ADC_Init_CALL_INSTANCE;

typedef struct _CMOCK_HAL_ADC_DeInit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  ADC_HandleTypeDef* Expected_hadc;

} CMOCK_HAL_ADC_DeInit_CALL_INSTANCE;

typedef struct _CMOCK_HAL_ADC_MspInit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  ADC_HandleTypeDef* Expected_hadc;

} CMOCK_HAL_ADC_MspInit_CALL_INSTANCE;

typedef struct _CMOCK_HAL_ADC_MspDeInit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  ADC_HandleTypeDef* Expected_hadc;

} CMOCK_HAL_ADC_MspDeInit_CALL_INSTANCE;

typedef struct _CMOCK_HAL_ADC_Start_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  ADC_HandleTypeDef* Expected_hadc;

} CMOCK_HAL_ADC_Start_CALL_INSTANCE;

typedef struct _CMOCK_HAL_ADC_Stop_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  ADC_HandleTypeDef* Expected_hadc;

} CMOCK_HAL_ADC_Stop_CALL_INSTANCE;

typedef struct _CMOCK_HAL_ADC_PollForConversion_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  ADC_HandleTypeDef* Expected_hadc;
  uint32_t Expected_Timeout;

} CMOCK_HAL_ADC_PollForConversion_CALL_INSTANCE;

typedef struct _CMOCK_HAL_ADC_PollForEvent_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  ADC_HandleTypeDef* Expected_hadc;
  uint32_t Expected_EventType;
  uint32_t Expected_Timeout;

} CMOCK_HAL_ADC_PollForEvent_CALL_INSTANCE;

typedef struct _CMOCK_HAL_ADC_Start_IT_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  ADC_HandleTypeDef* Expected_hadc;

} CMOCK_HAL_ADC_Start_IT_CALL_INSTANCE;

typedef struct _CMOCK_HAL_ADC_Stop_IT_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  ADC_HandleTypeDef* Expected_hadc;

} CMOCK_HAL_ADC_Stop_IT_CALL_INSTANCE;

typedef struct _CMOCK_HAL_ADC_IRQHandler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  ADC_HandleTypeDef* Expected_hadc;

} CMOCK_HAL_ADC_IRQHandler_CALL_INSTANCE;

typedef struct _CMOCK_HAL_ADC_Start_DMA_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  ADC_HandleTypeDef* Expected_hadc;
  uint32_t* Expected_pData;
  uint32_t Expected_Length;

} CMOCK_HAL_ADC_Start_DMA_CALL_INSTANCE;

typedef struct _CMOCK_HAL_ADC_Stop_DMA_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  ADC_HandleTypeDef* Expected_hadc;

} CMOCK_HAL_ADC_Stop_DMA_CALL_INSTANCE;

typedef struct _CMOCK_HAL_ADC_GetValue_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t ReturnVal;
  ADC_HandleTypeDef* Expected_hadc;

} CMOCK_HAL_ADC_GetValue_CALL_INSTANCE;

typedef struct _CMOCK_HAL_ADC_ConvCpltCallback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  ADC_HandleTypeDef* Expected_hadc;

} CMOCK_HAL_ADC_ConvCpltCallback_CALL_INSTANCE;

typedef struct _CMOCK_HAL_ADC_ConvHalfCpltCallback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  ADC_HandleTypeDef* Expected_hadc;

} CMOCK_HAL_ADC_ConvHalfCpltCallback_CALL_INSTANCE;

typedef struct _CMOCK_HAL_ADC_LevelOutOfWindowCallback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  ADC_HandleTypeDef* Expected_hadc;

} CMOCK_HAL_ADC_LevelOutOfWindowCallback_CALL_INSTANCE;

typedef struct _CMOCK_HAL_ADC_ErrorCallback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  ADC_HandleTypeDef* Expected_hadc;

} CMOCK_HAL_ADC_ErrorCallback_CALL_INSTANCE;

typedef struct _CMOCK_HAL_ADC_ConfigChannel_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  ADC_HandleTypeDef* Expected_hadc;
  ADC_ChannelConfTypeDef* Expected_sConfig;

} CMOCK_HAL_ADC_ConfigChannel_CALL_INSTANCE;

typedef struct _CMOCK_HAL_ADC_AnalogWDGConfig_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  ADC_HandleTypeDef* Expected_hadc;
  ADC_AnalogWDGConfTypeDef* Expected_AnalogWDGConfig;

} CMOCK_HAL_ADC_AnalogWDGConfig_CALL_INSTANCE;

typedef struct _CMOCK_HAL_ADC_GetState_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t ReturnVal;
  ADC_HandleTypeDef* Expected_hadc;

} CMOCK_HAL_ADC_GetState_CALL_INSTANCE;

typedef struct _CMOCK_HAL_ADC_GetError_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t ReturnVal;
  ADC_HandleTypeDef* Expected_hadc;

} CMOCK_HAL_ADC_GetError_CALL_INSTANCE;

static struct Mockstm32f4xx_hal_adcInstance
{
  CMOCK_MEM_INDEX_TYPE HAL_ADC_Init_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_ADC_DeInit_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_ADC_MspInit_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_ADC_MspDeInit_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_ADC_Start_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_ADC_Stop_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_ADC_PollForConversion_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_ADC_PollForEvent_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_ADC_Start_IT_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_ADC_Stop_IT_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_ADC_IRQHandler_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_ADC_Start_DMA_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_ADC_Stop_DMA_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_ADC_GetValue_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_ADC_ConvCpltCallback_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_ADC_ConvHalfCpltCallback_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_ADC_LevelOutOfWindowCallback_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_ADC_ErrorCallback_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_ADC_ConfigChannel_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_ADC_AnalogWDGConfig_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_ADC_GetState_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_ADC_GetError_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockstm32f4xx_hal_adc_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.HAL_ADC_Init_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_ADC_Init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_ADC_DeInit_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_ADC_DeInit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_ADC_MspInit_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_ADC_MspInit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_ADC_MspDeInit_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_ADC_MspDeInit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_ADC_Start_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_ADC_Start);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_ADC_Stop_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_ADC_Stop);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_ADC_PollForConversion_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_ADC_PollForConversion);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_ADC_PollForEvent_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_ADC_PollForEvent);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_ADC_Start_IT_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_ADC_Start_IT);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_ADC_Stop_IT_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_ADC_Stop_IT);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_ADC_IRQHandler_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_ADC_IRQHandler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_ADC_Start_DMA_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_ADC_Start_DMA);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_ADC_Stop_DMA_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_ADC_Stop_DMA);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_ADC_GetValue_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_ADC_GetValue);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_ADC_ConvCpltCallback_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_ADC_ConvCpltCallback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_ADC_ConvHalfCpltCallback_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_ADC_ConvHalfCpltCallback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_ADC_LevelOutOfWindowCallback_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_ADC_LevelOutOfWindowCallback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_ADC_ErrorCallback_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_ADC_ErrorCallback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_ADC_ConfigChannel_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_ADC_ConfigChannel);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_ADC_AnalogWDGConfig_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_ADC_AnalogWDGConfig);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_ADC_GetState_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_ADC_GetState);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_ADC_GetError_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_ADC_GetError);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockstm32f4xx_hal_adc_Init(void)
{
  Mockstm32f4xx_hal_adc_Destroy();
}

void Mockstm32f4xx_hal_adc_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

HAL_StatusTypeDef HAL_ADC_Init(ADC_HandleTypeDef* hadc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_ADC_Init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_ADC_Init);
  cmock_call_instance = (CMOCK_HAL_ADC_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_ADC_Init_CallInstance);
  Mock.HAL_ADC_Init_CallInstance = CMock_Guts_MemNext(Mock.HAL_ADC_Init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_Init,CMockString_hadc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hadc), (void*)(hadc), sizeof(ADC_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_ADC_Init(CMOCK_HAL_ADC_Init_CALL_INSTANCE* cmock_call_instance, ADC_HandleTypeDef* hadc)
{
  cmock_call_instance->Expected_hadc = hadc;
}

void HAL_ADC_Init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ADC_Init_CALL_INSTANCE));
  CMOCK_HAL_ADC_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ADC_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ADC_Init_CallInstance = CMock_Guts_MemChain(Mock.HAL_ADC_Init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_ADC_Init(cmock_call_instance, hadc);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_ADC_DeInit(ADC_HandleTypeDef* hadc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_ADC_DeInit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_ADC_DeInit);
  cmock_call_instance = (CMOCK_HAL_ADC_DeInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_ADC_DeInit_CallInstance);
  Mock.HAL_ADC_DeInit_CallInstance = CMock_Guts_MemNext(Mock.HAL_ADC_DeInit_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_DeInit,CMockString_hadc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hadc), (void*)(hadc), sizeof(ADC_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_ADC_DeInit(CMOCK_HAL_ADC_DeInit_CALL_INSTANCE* cmock_call_instance, ADC_HandleTypeDef* hadc)
{
  cmock_call_instance->Expected_hadc = hadc;
}

void HAL_ADC_DeInit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ADC_DeInit_CALL_INSTANCE));
  CMOCK_HAL_ADC_DeInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ADC_DeInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ADC_DeInit_CallInstance = CMock_Guts_MemChain(Mock.HAL_ADC_DeInit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_ADC_DeInit(cmock_call_instance, hadc);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

void HAL_ADC_MspInit(ADC_HandleTypeDef* hadc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_ADC_MspInit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_ADC_MspInit);
  cmock_call_instance = (CMOCK_HAL_ADC_MspInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_ADC_MspInit_CallInstance);
  Mock.HAL_ADC_MspInit_CallInstance = CMock_Guts_MemNext(Mock.HAL_ADC_MspInit_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_MspInit,CMockString_hadc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hadc), (void*)(hadc), sizeof(ADC_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_ADC_MspInit(CMOCK_HAL_ADC_MspInit_CALL_INSTANCE* cmock_call_instance, ADC_HandleTypeDef* hadc)
{
  cmock_call_instance->Expected_hadc = hadc;
}

void HAL_ADC_MspInit_CMockExpect(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ADC_MspInit_CALL_INSTANCE));
  CMOCK_HAL_ADC_MspInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ADC_MspInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ADC_MspInit_CallInstance = CMock_Guts_MemChain(Mock.HAL_ADC_MspInit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_ADC_MspInit(cmock_call_instance, hadc);
}

void HAL_ADC_MspDeInit(ADC_HandleTypeDef* hadc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_ADC_MspDeInit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_ADC_MspDeInit);
  cmock_call_instance = (CMOCK_HAL_ADC_MspDeInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_ADC_MspDeInit_CallInstance);
  Mock.HAL_ADC_MspDeInit_CallInstance = CMock_Guts_MemNext(Mock.HAL_ADC_MspDeInit_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_MspDeInit,CMockString_hadc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hadc), (void*)(hadc), sizeof(ADC_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_ADC_MspDeInit(CMOCK_HAL_ADC_MspDeInit_CALL_INSTANCE* cmock_call_instance, ADC_HandleTypeDef* hadc)
{
  cmock_call_instance->Expected_hadc = hadc;
}

void HAL_ADC_MspDeInit_CMockExpect(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ADC_MspDeInit_CALL_INSTANCE));
  CMOCK_HAL_ADC_MspDeInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ADC_MspDeInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ADC_MspDeInit_CallInstance = CMock_Guts_MemChain(Mock.HAL_ADC_MspDeInit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_ADC_MspDeInit(cmock_call_instance, hadc);
}

HAL_StatusTypeDef HAL_ADC_Start(ADC_HandleTypeDef* hadc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_ADC_Start_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_ADC_Start);
  cmock_call_instance = (CMOCK_HAL_ADC_Start_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_ADC_Start_CallInstance);
  Mock.HAL_ADC_Start_CallInstance = CMock_Guts_MemNext(Mock.HAL_ADC_Start_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_Start,CMockString_hadc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hadc), (void*)(hadc), sizeof(ADC_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_ADC_Start(CMOCK_HAL_ADC_Start_CALL_INSTANCE* cmock_call_instance, ADC_HandleTypeDef* hadc)
{
  cmock_call_instance->Expected_hadc = hadc;
}

void HAL_ADC_Start_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ADC_Start_CALL_INSTANCE));
  CMOCK_HAL_ADC_Start_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ADC_Start_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ADC_Start_CallInstance = CMock_Guts_MemChain(Mock.HAL_ADC_Start_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_ADC_Start(cmock_call_instance, hadc);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_ADC_Stop(ADC_HandleTypeDef* hadc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_ADC_Stop_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_ADC_Stop);
  cmock_call_instance = (CMOCK_HAL_ADC_Stop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_ADC_Stop_CallInstance);
  Mock.HAL_ADC_Stop_CallInstance = CMock_Guts_MemNext(Mock.HAL_ADC_Stop_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_Stop,CMockString_hadc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hadc), (void*)(hadc), sizeof(ADC_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_ADC_Stop(CMOCK_HAL_ADC_Stop_CALL_INSTANCE* cmock_call_instance, ADC_HandleTypeDef* hadc)
{
  cmock_call_instance->Expected_hadc = hadc;
}

void HAL_ADC_Stop_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ADC_Stop_CALL_INSTANCE));
  CMOCK_HAL_ADC_Stop_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ADC_Stop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ADC_Stop_CallInstance = CMock_Guts_MemChain(Mock.HAL_ADC_Stop_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_ADC_Stop(cmock_call_instance, hadc);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_ADC_PollForConversion(ADC_HandleTypeDef* hadc, uint32_t Timeout)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_ADC_PollForConversion_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_ADC_PollForConversion);
  cmock_call_instance = (CMOCK_HAL_ADC_PollForConversion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_ADC_PollForConversion_CallInstance);
  Mock.HAL_ADC_PollForConversion_CallInstance = CMock_Guts_MemNext(Mock.HAL_ADC_PollForConversion_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_PollForConversion,CMockString_hadc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hadc), (void*)(hadc), sizeof(ADC_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_PollForConversion,CMockString_Timeout);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_Timeout, Timeout, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_ADC_PollForConversion(CMOCK_HAL_ADC_PollForConversion_CALL_INSTANCE* cmock_call_instance, ADC_HandleTypeDef* hadc, uint32_t Timeout)
{
  cmock_call_instance->Expected_hadc = hadc;
  cmock_call_instance->Expected_Timeout = Timeout;
}

void HAL_ADC_PollForConversion_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ADC_PollForConversion_CALL_INSTANCE));
  CMOCK_HAL_ADC_PollForConversion_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ADC_PollForConversion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ADC_PollForConversion_CallInstance = CMock_Guts_MemChain(Mock.HAL_ADC_PollForConversion_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_ADC_PollForConversion(cmock_call_instance, hadc, Timeout);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_ADC_PollForEvent(ADC_HandleTypeDef* hadc, uint32_t EventType, uint32_t Timeout)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_ADC_PollForEvent_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_ADC_PollForEvent);
  cmock_call_instance = (CMOCK_HAL_ADC_PollForEvent_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_ADC_PollForEvent_CallInstance);
  Mock.HAL_ADC_PollForEvent_CallInstance = CMock_Guts_MemNext(Mock.HAL_ADC_PollForEvent_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_PollForEvent,CMockString_hadc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hadc), (void*)(hadc), sizeof(ADC_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_PollForEvent,CMockString_EventType);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_EventType, EventType, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_PollForEvent,CMockString_Timeout);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_Timeout, Timeout, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_ADC_PollForEvent(CMOCK_HAL_ADC_PollForEvent_CALL_INSTANCE* cmock_call_instance, ADC_HandleTypeDef* hadc, uint32_t EventType, uint32_t Timeout)
{
  cmock_call_instance->Expected_hadc = hadc;
  cmock_call_instance->Expected_EventType = EventType;
  cmock_call_instance->Expected_Timeout = Timeout;
}

void HAL_ADC_PollForEvent_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc, uint32_t EventType, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ADC_PollForEvent_CALL_INSTANCE));
  CMOCK_HAL_ADC_PollForEvent_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ADC_PollForEvent_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ADC_PollForEvent_CallInstance = CMock_Guts_MemChain(Mock.HAL_ADC_PollForEvent_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_ADC_PollForEvent(cmock_call_instance, hadc, EventType, Timeout);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_ADC_Start_IT(ADC_HandleTypeDef* hadc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_ADC_Start_IT_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_ADC_Start_IT);
  cmock_call_instance = (CMOCK_HAL_ADC_Start_IT_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_ADC_Start_IT_CallInstance);
  Mock.HAL_ADC_Start_IT_CallInstance = CMock_Guts_MemNext(Mock.HAL_ADC_Start_IT_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_Start_IT,CMockString_hadc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hadc), (void*)(hadc), sizeof(ADC_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_ADC_Start_IT(CMOCK_HAL_ADC_Start_IT_CALL_INSTANCE* cmock_call_instance, ADC_HandleTypeDef* hadc)
{
  cmock_call_instance->Expected_hadc = hadc;
}

void HAL_ADC_Start_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ADC_Start_IT_CALL_INSTANCE));
  CMOCK_HAL_ADC_Start_IT_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ADC_Start_IT_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ADC_Start_IT_CallInstance = CMock_Guts_MemChain(Mock.HAL_ADC_Start_IT_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_ADC_Start_IT(cmock_call_instance, hadc);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_ADC_Stop_IT(ADC_HandleTypeDef* hadc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_ADC_Stop_IT_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_ADC_Stop_IT);
  cmock_call_instance = (CMOCK_HAL_ADC_Stop_IT_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_ADC_Stop_IT_CallInstance);
  Mock.HAL_ADC_Stop_IT_CallInstance = CMock_Guts_MemNext(Mock.HAL_ADC_Stop_IT_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_Stop_IT,CMockString_hadc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hadc), (void*)(hadc), sizeof(ADC_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_ADC_Stop_IT(CMOCK_HAL_ADC_Stop_IT_CALL_INSTANCE* cmock_call_instance, ADC_HandleTypeDef* hadc)
{
  cmock_call_instance->Expected_hadc = hadc;
}

void HAL_ADC_Stop_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ADC_Stop_IT_CALL_INSTANCE));
  CMOCK_HAL_ADC_Stop_IT_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ADC_Stop_IT_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ADC_Stop_IT_CallInstance = CMock_Guts_MemChain(Mock.HAL_ADC_Stop_IT_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_ADC_Stop_IT(cmock_call_instance, hadc);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

void HAL_ADC_IRQHandler(ADC_HandleTypeDef* hadc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_ADC_IRQHandler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_ADC_IRQHandler);
  cmock_call_instance = (CMOCK_HAL_ADC_IRQHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_ADC_IRQHandler_CallInstance);
  Mock.HAL_ADC_IRQHandler_CallInstance = CMock_Guts_MemNext(Mock.HAL_ADC_IRQHandler_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_IRQHandler,CMockString_hadc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hadc), (void*)(hadc), sizeof(ADC_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_ADC_IRQHandler(CMOCK_HAL_ADC_IRQHandler_CALL_INSTANCE* cmock_call_instance, ADC_HandleTypeDef* hadc)
{
  cmock_call_instance->Expected_hadc = hadc;
}

void HAL_ADC_IRQHandler_CMockExpect(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ADC_IRQHandler_CALL_INSTANCE));
  CMOCK_HAL_ADC_IRQHandler_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ADC_IRQHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ADC_IRQHandler_CallInstance = CMock_Guts_MemChain(Mock.HAL_ADC_IRQHandler_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_ADC_IRQHandler(cmock_call_instance, hadc);
}

HAL_StatusTypeDef HAL_ADC_Start_DMA(ADC_HandleTypeDef* hadc, uint32_t* pData, uint32_t Length)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_ADC_Start_DMA_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_ADC_Start_DMA);
  cmock_call_instance = (CMOCK_HAL_ADC_Start_DMA_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_ADC_Start_DMA_CallInstance);
  Mock.HAL_ADC_Start_DMA_CallInstance = CMock_Guts_MemNext(Mock.HAL_ADC_Start_DMA_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_Start_DMA,CMockString_hadc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hadc), (void*)(hadc), sizeof(ADC_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_Start_DMA,CMockString_pData);
    if (cmock_call_instance->Expected_pData == NULL)
      { UNITY_TEST_ASSERT_NULL(pData, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_pData, pData, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_Start_DMA,CMockString_Length);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_Length, Length, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_ADC_Start_DMA(CMOCK_HAL_ADC_Start_DMA_CALL_INSTANCE* cmock_call_instance, ADC_HandleTypeDef* hadc, uint32_t* pData, uint32_t Length)
{
  cmock_call_instance->Expected_hadc = hadc;
  cmock_call_instance->Expected_pData = pData;
  cmock_call_instance->Expected_Length = Length;
}

void HAL_ADC_Start_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc, uint32_t* pData, uint32_t Length, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ADC_Start_DMA_CALL_INSTANCE));
  CMOCK_HAL_ADC_Start_DMA_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ADC_Start_DMA_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ADC_Start_DMA_CallInstance = CMock_Guts_MemChain(Mock.HAL_ADC_Start_DMA_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_ADC_Start_DMA(cmock_call_instance, hadc, pData, Length);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_ADC_Stop_DMA(ADC_HandleTypeDef* hadc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_ADC_Stop_DMA_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_ADC_Stop_DMA);
  cmock_call_instance = (CMOCK_HAL_ADC_Stop_DMA_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_ADC_Stop_DMA_CallInstance);
  Mock.HAL_ADC_Stop_DMA_CallInstance = CMock_Guts_MemNext(Mock.HAL_ADC_Stop_DMA_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_Stop_DMA,CMockString_hadc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hadc), (void*)(hadc), sizeof(ADC_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_ADC_Stop_DMA(CMOCK_HAL_ADC_Stop_DMA_CALL_INSTANCE* cmock_call_instance, ADC_HandleTypeDef* hadc)
{
  cmock_call_instance->Expected_hadc = hadc;
}

void HAL_ADC_Stop_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ADC_Stop_DMA_CALL_INSTANCE));
  CMOCK_HAL_ADC_Stop_DMA_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ADC_Stop_DMA_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ADC_Stop_DMA_CallInstance = CMock_Guts_MemChain(Mock.HAL_ADC_Stop_DMA_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_ADC_Stop_DMA(cmock_call_instance, hadc);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

uint32_t HAL_ADC_GetValue(ADC_HandleTypeDef* hadc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_ADC_GetValue_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_ADC_GetValue);
  cmock_call_instance = (CMOCK_HAL_ADC_GetValue_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_ADC_GetValue_CallInstance);
  Mock.HAL_ADC_GetValue_CallInstance = CMock_Guts_MemNext(Mock.HAL_ADC_GetValue_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_GetValue,CMockString_hadc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hadc), (void*)(hadc), sizeof(ADC_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_ADC_GetValue(CMOCK_HAL_ADC_GetValue_CALL_INSTANCE* cmock_call_instance, ADC_HandleTypeDef* hadc)
{
  cmock_call_instance->Expected_hadc = hadc;
}

void HAL_ADC_GetValue_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ADC_GetValue_CALL_INSTANCE));
  CMOCK_HAL_ADC_GetValue_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ADC_GetValue_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ADC_GetValue_CallInstance = CMock_Guts_MemChain(Mock.HAL_ADC_GetValue_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_ADC_GetValue(cmock_call_instance, hadc);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef* hadc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_ADC_ConvCpltCallback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_ADC_ConvCpltCallback);
  cmock_call_instance = (CMOCK_HAL_ADC_ConvCpltCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_ADC_ConvCpltCallback_CallInstance);
  Mock.HAL_ADC_ConvCpltCallback_CallInstance = CMock_Guts_MemNext(Mock.HAL_ADC_ConvCpltCallback_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_ConvCpltCallback,CMockString_hadc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hadc), (void*)(hadc), sizeof(ADC_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_ADC_ConvCpltCallback(CMOCK_HAL_ADC_ConvCpltCallback_CALL_INSTANCE* cmock_call_instance, ADC_HandleTypeDef* hadc)
{
  cmock_call_instance->Expected_hadc = hadc;
}

void HAL_ADC_ConvCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ADC_ConvCpltCallback_CALL_INSTANCE));
  CMOCK_HAL_ADC_ConvCpltCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ADC_ConvCpltCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ADC_ConvCpltCallback_CallInstance = CMock_Guts_MemChain(Mock.HAL_ADC_ConvCpltCallback_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_ADC_ConvCpltCallback(cmock_call_instance, hadc);
}

void HAL_ADC_ConvHalfCpltCallback(ADC_HandleTypeDef* hadc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_ADC_ConvHalfCpltCallback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_ADC_ConvHalfCpltCallback);
  cmock_call_instance = (CMOCK_HAL_ADC_ConvHalfCpltCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_ADC_ConvHalfCpltCallback_CallInstance);
  Mock.HAL_ADC_ConvHalfCpltCallback_CallInstance = CMock_Guts_MemNext(Mock.HAL_ADC_ConvHalfCpltCallback_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_ConvHalfCpltCallback,CMockString_hadc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hadc), (void*)(hadc), sizeof(ADC_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_ADC_ConvHalfCpltCallback(CMOCK_HAL_ADC_ConvHalfCpltCallback_CALL_INSTANCE* cmock_call_instance, ADC_HandleTypeDef* hadc)
{
  cmock_call_instance->Expected_hadc = hadc;
}

void HAL_ADC_ConvHalfCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ADC_ConvHalfCpltCallback_CALL_INSTANCE));
  CMOCK_HAL_ADC_ConvHalfCpltCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ADC_ConvHalfCpltCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ADC_ConvHalfCpltCallback_CallInstance = CMock_Guts_MemChain(Mock.HAL_ADC_ConvHalfCpltCallback_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_ADC_ConvHalfCpltCallback(cmock_call_instance, hadc);
}

void HAL_ADC_LevelOutOfWindowCallback(ADC_HandleTypeDef* hadc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_ADC_LevelOutOfWindowCallback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_ADC_LevelOutOfWindowCallback);
  cmock_call_instance = (CMOCK_HAL_ADC_LevelOutOfWindowCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_ADC_LevelOutOfWindowCallback_CallInstance);
  Mock.HAL_ADC_LevelOutOfWindowCallback_CallInstance = CMock_Guts_MemNext(Mock.HAL_ADC_LevelOutOfWindowCallback_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_LevelOutOfWindowCallback,CMockString_hadc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hadc), (void*)(hadc), sizeof(ADC_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_ADC_LevelOutOfWindowCallback(CMOCK_HAL_ADC_LevelOutOfWindowCallback_CALL_INSTANCE* cmock_call_instance, ADC_HandleTypeDef* hadc)
{
  cmock_call_instance->Expected_hadc = hadc;
}

void HAL_ADC_LevelOutOfWindowCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ADC_LevelOutOfWindowCallback_CALL_INSTANCE));
  CMOCK_HAL_ADC_LevelOutOfWindowCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ADC_LevelOutOfWindowCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ADC_LevelOutOfWindowCallback_CallInstance = CMock_Guts_MemChain(Mock.HAL_ADC_LevelOutOfWindowCallback_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_ADC_LevelOutOfWindowCallback(cmock_call_instance, hadc);
}

void HAL_ADC_ErrorCallback(ADC_HandleTypeDef* hadc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_ADC_ErrorCallback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_ADC_ErrorCallback);
  cmock_call_instance = (CMOCK_HAL_ADC_ErrorCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_ADC_ErrorCallback_CallInstance);
  Mock.HAL_ADC_ErrorCallback_CallInstance = CMock_Guts_MemNext(Mock.HAL_ADC_ErrorCallback_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_ErrorCallback,CMockString_hadc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hadc), (void*)(hadc), sizeof(ADC_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_ADC_ErrorCallback(CMOCK_HAL_ADC_ErrorCallback_CALL_INSTANCE* cmock_call_instance, ADC_HandleTypeDef* hadc)
{
  cmock_call_instance->Expected_hadc = hadc;
}

void HAL_ADC_ErrorCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ADC_ErrorCallback_CALL_INSTANCE));
  CMOCK_HAL_ADC_ErrorCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ADC_ErrorCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ADC_ErrorCallback_CallInstance = CMock_Guts_MemChain(Mock.HAL_ADC_ErrorCallback_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_ADC_ErrorCallback(cmock_call_instance, hadc);
}

HAL_StatusTypeDef HAL_ADC_ConfigChannel(ADC_HandleTypeDef* hadc, ADC_ChannelConfTypeDef* sConfig)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_ADC_ConfigChannel_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_ADC_ConfigChannel);
  cmock_call_instance = (CMOCK_HAL_ADC_ConfigChannel_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_ADC_ConfigChannel_CallInstance);
  Mock.HAL_ADC_ConfigChannel_CallInstance = CMock_Guts_MemNext(Mock.HAL_ADC_ConfigChannel_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_ConfigChannel,CMockString_hadc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hadc), (void*)(hadc), sizeof(ADC_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_ConfigChannel,CMockString_sConfig);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_sConfig), (void*)(sConfig), sizeof(ADC_ChannelConfTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_ADC_ConfigChannel(CMOCK_HAL_ADC_ConfigChannel_CALL_INSTANCE* cmock_call_instance, ADC_HandleTypeDef* hadc, ADC_ChannelConfTypeDef* sConfig)
{
  cmock_call_instance->Expected_hadc = hadc;
  cmock_call_instance->Expected_sConfig = sConfig;
}

void HAL_ADC_ConfigChannel_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc, ADC_ChannelConfTypeDef* sConfig, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ADC_ConfigChannel_CALL_INSTANCE));
  CMOCK_HAL_ADC_ConfigChannel_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ADC_ConfigChannel_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ADC_ConfigChannel_CallInstance = CMock_Guts_MemChain(Mock.HAL_ADC_ConfigChannel_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_ADC_ConfigChannel(cmock_call_instance, hadc, sConfig);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_ADC_AnalogWDGConfig(ADC_HandleTypeDef* hadc, ADC_AnalogWDGConfTypeDef* AnalogWDGConfig)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_ADC_AnalogWDGConfig_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_ADC_AnalogWDGConfig);
  cmock_call_instance = (CMOCK_HAL_ADC_AnalogWDGConfig_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_ADC_AnalogWDGConfig_CallInstance);
  Mock.HAL_ADC_AnalogWDGConfig_CallInstance = CMock_Guts_MemNext(Mock.HAL_ADC_AnalogWDGConfig_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_AnalogWDGConfig,CMockString_hadc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hadc), (void*)(hadc), sizeof(ADC_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_AnalogWDGConfig,CMockString_AnalogWDGConfig);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_AnalogWDGConfig), (void*)(AnalogWDGConfig), sizeof(ADC_AnalogWDGConfTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_ADC_AnalogWDGConfig(CMOCK_HAL_ADC_AnalogWDGConfig_CALL_INSTANCE* cmock_call_instance, ADC_HandleTypeDef* hadc, ADC_AnalogWDGConfTypeDef* AnalogWDGConfig)
{
  cmock_call_instance->Expected_hadc = hadc;
  cmock_call_instance->Expected_AnalogWDGConfig = AnalogWDGConfig;
}

void HAL_ADC_AnalogWDGConfig_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc, ADC_AnalogWDGConfTypeDef* AnalogWDGConfig, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ADC_AnalogWDGConfig_CALL_INSTANCE));
  CMOCK_HAL_ADC_AnalogWDGConfig_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ADC_AnalogWDGConfig_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ADC_AnalogWDGConfig_CallInstance = CMock_Guts_MemChain(Mock.HAL_ADC_AnalogWDGConfig_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_ADC_AnalogWDGConfig(cmock_call_instance, hadc, AnalogWDGConfig);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

uint32_t HAL_ADC_GetState(ADC_HandleTypeDef* hadc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_ADC_GetState_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_ADC_GetState);
  cmock_call_instance = (CMOCK_HAL_ADC_GetState_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_ADC_GetState_CallInstance);
  Mock.HAL_ADC_GetState_CallInstance = CMock_Guts_MemNext(Mock.HAL_ADC_GetState_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_GetState,CMockString_hadc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hadc), (void*)(hadc), sizeof(ADC_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_ADC_GetState(CMOCK_HAL_ADC_GetState_CALL_INSTANCE* cmock_call_instance, ADC_HandleTypeDef* hadc)
{
  cmock_call_instance->Expected_hadc = hadc;
}

void HAL_ADC_GetState_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ADC_GetState_CALL_INSTANCE));
  CMOCK_HAL_ADC_GetState_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ADC_GetState_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ADC_GetState_CallInstance = CMock_Guts_MemChain(Mock.HAL_ADC_GetState_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_ADC_GetState(cmock_call_instance, hadc);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

uint32_t HAL_ADC_GetError(ADC_HandleTypeDef* hadc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_ADC_GetError_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_ADC_GetError);
  cmock_call_instance = (CMOCK_HAL_ADC_GetError_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_ADC_GetError_CallInstance);
  Mock.HAL_ADC_GetError_CallInstance = CMock_Guts_MemNext(Mock.HAL_ADC_GetError_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_ADC_GetError,CMockString_hadc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hadc), (void*)(hadc), sizeof(ADC_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_ADC_GetError(CMOCK_HAL_ADC_GetError_CALL_INSTANCE* cmock_call_instance, ADC_HandleTypeDef* hadc)
{
  cmock_call_instance->Expected_hadc = hadc;
}

void HAL_ADC_GetError_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ADC_GetError_CALL_INSTANCE));
  CMOCK_HAL_ADC_GetError_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ADC_GetError_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ADC_GetError_CallInstance = CMock_Guts_MemChain(Mock.HAL_ADC_GetError_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_ADC_GetError(cmock_call_instance, hadc);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

