/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSTATEFUNCTIONSSHARED_H
#define _MOCKSTATEFUNCTIONSSHARED_H

#include "unity.h"
#include "StateFunctionsShared.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void MockStateFunctionsShared_Init(void);
void MockStateFunctionsShared_Destroy(void);
void MockStateFunctionsShared_Verify(void);




#define disconnectContactors_Expect(isContactorError) disconnectContactors_CMockExpect(__LINE__, isContactorError)
void disconnectContactors_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t isContactorError);
#define dischargeDisconnectedDuringContactorSetting_ExpectAndReturn(dischargeSense, hasDischargeBeenSet, cmock_retval) dischargeDisconnectedDuringContactorSetting_CMockExpectAndReturn(__LINE__, dischargeSense, hasDischargeBeenSet, cmock_retval)
void dischargeDisconnectedDuringContactorSetting_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const uint8_t dischargeSense, uint8_t hasDischargeBeenSet, uint8_t cmock_to_return);
#define chargeDisconnectedDuringContactorSetting_ExpectAndReturn(chargeSense, hasChargeBeenSet, cmock_retval) chargeDisconnectedDuringContactorSetting_CMockExpectAndReturn(__LINE__, chargeSense, hasChargeBeenSet, cmock_retval)
void chargeDisconnectedDuringContactorSetting_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const uint8_t chargeSense, uint8_t hasChargeBeenSet, uint8_t cmock_to_return);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
