= Aux BMS Tests

== HeartBeat Test
----
Elapsed 5000ms{
	Expect 5 Heartbeat CAN messages (0x720)
}
----

== Aux Test
----
Elapsed 1000ms{
	Expect 10 Aux CAN messages (0x721)
}
----

== Test Cases

=== Expected Outputs
[options="header"]
|===
| Test | CAN_ADDRESS | DATA_INDEX | TIME_FRAME
| Precharge State |  0x721 | 0-2 |  100ms 
| Aux Voltage |  0x721 | 3-7 |  100ms 
| Discharge Contactor State | 0x721 |  2 |  100ms
| Charge Contactor State | 0x721 |  1 |  100ms
| Common Contactor State |  0x721  | 0 |  100ms 
| Contactor Error |  0x721  | 10 |  100ms 
| All Contactors On |  0x721 | 0-2 |  1000ms
| Common and Discharge Cycle Test |  0x721 | 0-2 |  1000ms
| Discharge Off |  0x721  |  0-2 |  1000ms 
| Safety |  0x721 | 0-2 |  1000ms 
| Allow Charge |  0x721  | 9 |  1000ms
| Strobe BMS Light |  0x721 | 8 |  200ms 
| Max Cell Voltage |  0x721  | 0-2 |  1000ms
| Max Cell Voltage In Range |  0x721  | 0-2 |  1000ms
| Min Cell Voltage |  0x721  | 0-2 |  1000ms
| Min Cell Voltage In Range |  0x721  | 0-2 |  1000ms |
|===

= Contactor Tests

== Precharge State Test
----
Elapsed TIME_FRAME{
    	Expect (CONTACTOR_CAN_MESSAGE(CAN_ADDRESS)[DATA_INDEX])
}
----

== Aux Voltage Test 
----
Input Voltage From Voltage Source
Elapsed TIME_FRAME{
    	Expect (VOLTAGE_CAN_MESSAGE(CAN_ADDRESS)[DATA_INDEX] == Input Voltage)
}
----

== Discharge Contactor State Test
----
//Start Test
Within TIME_FRAME{
	Expect (CONTACTOR_CAN_MESSAGE(CAN_ADDRESS)[DATA_INDEX])
}
----

== Charge Contactor State Test
----
//Start Test
Within TIME_FRAME{
	Expect (CONTACTOR_CAN_MESSAGE(CAN_ADDRESS)[DATA_INDEX])
}
----

== Common Contactor State Test
----
//Start Test
Within TIME_FRAME{
	Expect (CONTACTOR_CAN_MESSAGE(CAN_ADDRESS)[DATA_INDEX])
}
----

== Contactor Error Test
----
//Remove A Contactor In DONE State
Within TIME_FRAME{
	Expect (CONTACTOR_CAN_MESSAGE(CAN_ADDRESS)[DATA_INDEX] == 0b000)
}
----

== All Contactor On Test
----
//Start Test
Within TIME_FRAME{
    Expect (CONTACTOR_CAN_MESSAGE(CAN_ADDRESS)[DATA_INDEX] == 0b001) 
        COMMON LED ON
        CHARGE LED OFF
        DISCHARGE LED OFF
}
Within TIME_FRAME{
    Expect (CONTACTOR_CAN_MESSAGE(CAN_ADDRESS)[DATA_INDEX] == 0b011) 
        COMMON LED ON
        CHARGE LED ON
        DISCHARGE LED OFF
}
Within TIME_FRAME{
    Expect (CONTACTOR_CAN_MESSAGE(CAN_ADDRESS)[DATA_INDEX] == 0b111) 
        COMMON LED ON
        CHARGE LED ON
        DISCHARGE LED ON
}
Within TIME_FRAME{
    Expect (CONTACTOR_CAN_MESSAGE(CAN_ADDRESS)[DATA_INDEX] == 0b111) 
   	    COMMON LED ON
   	    CHARGE LED ON
   	    DISCHARGE LED ON
}
----

== Common and Discharge Cycle Test
----
//Start Test With Only Common Contactor Connected
Within TIME_FRAME{
    Expect (CONTACTOR_CAN_MESSAGE(CAN_ADDRESS)[DATA_INDEX] == 0b001) 
        COMMON LED ON
        CHARGE LED OFF
        DISCHARGE LED OFF
}
Within TIME_FRAME{
    Expect (CONTACTOR_CAN_MESSAGE(CAN_ADDRESS)[DATA_INDEX] == 0b001) 
        COMMON LED ON
        CHARGE LED OFF
        DISCHARGE LED OFF
}
Within TIME_FRAME{
    Expect (CONTACTOR_CAN_MESSAGE(CAN_ADDRESS)[DATA_INDEX] == 0b001) 
        COMMON LED ON
        CHARGE LED OFF
        DISCHARGE LED OFF
}
Within TIME_FRAME{
    Expect (CONTACTOR_CAN_MESSAGE(CAN_ADDRESS)[DATA_INDEX] == 0b001) 
		COMMON LED ON
        CHARGE LED OFF
        DISCHARGE LED OFF
}
----

== Discharge Off Test
----
//Start Discharge Test
Within TIME_FRAME{
    Expect (CONTACTOR_CAN_MESSAGE(CAN_ADDRESS)[DATA_INDEX] == 0b101) 
        COMMON LED ON
        CHARGE LED ON
        DISCHARGE LED OFF
}
----

== Safety Test
----
//Start Safety Test
Within TIME_FRAME{
    Expect (CONTACTOR_CAN_MESSAGE(CAN_ADDRESS)[DATA_INDEX] == 0b000) 
        COMMON LED OFF
        CHARGE LED OFF
        DISCHARGE LED OFF
}
----

== Allow Charge Test
----
Input Voltage < MAX_CELL_VOLTAGE And Charge Enable On
    Within TIME_FRAME{
        COMMON LED ON
        CHARGE LED ON
        DISCHARGE LED OFF
}
----

== Strobe Light Test
----
Input(BMS_CAN_MESSAGE(CAN_ADDRESS) == 0x200)
    Within TIME_FRAME{
        Expect (LIGHTS_CAN_MESSAGE(LIGHTS_CAN_ADDRESS) == 0x20)
}
----

== Max Cell Voltage 
----
//Start with common and charge contactors on
Set Input Voltage > MAX_CELL_VOLTAGE
    Within TIME_FRAME{
	Expect (CONTACTOR_CAN_MESSAGE(CAN_ADDRESS)[DATA_INDEX] == 0b001) 
        COMMON LED ON
        CHARGE LED OFF
        DISCHARGE LED OFF
}
----

== Max Cell Voltage In Range
----
//Start with common and charge contactors on
Set Input Voltage < MAX_CELL_VOLTAGE
    Within TIME_FRAME{
	Expect (CONTACTOR_CAN_MESSAGE(CAN_ADDRESS)[DATA_INDEX] == 0b011) 
        COMMON LED ON
        CHARGE LED ON
        DISCHARGE LED OFF
}
----

== Min Cell Voltage 
----
//Start with common and discharge contactors on
Set Input Voltage < MIN_CELL_VOLTAGE
    Within TIME_FRAME{
	Expect (CONTACTOR_CAN_MESSAGE(CAN_ADDRESS)[DATA_INDEX] == 0b001) 
        COMMON LED ON
        DISCHARGE LED OFF
        CHARGE LED OFF 
}
----

== Min Cell Voltage In Range 
----
//Start with common and discharge contactors on
Set Input Voltage > MIN_CELL_VOLTAGE
    Within TIME_FRAME{
	Expect (CONTACTOR_CAN_MESSAGE(CAN_ADDRESS)[DATA_INDEX] == 0b101) 
        COMMON LED ON
        DISCHARGE LED ON
        CHARGE LED OFF
}
----

