/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKCHECKCONTACTORSET_H
#define _MOCKCHECKCONTACTORSET_H

#include "unity.h"
#include "CheckContactorSet.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void MockCheckContactorSet_Init(void);
void MockCheckContactorSet_Destroy(void);
void MockCheckContactorSet_Verify(void);




#define readCurrentThroughContactors_ExpectAndReturn(cmock_retval) readCurrentThroughContactors_CMockExpectAndReturn(__LINE__, cmock_retval)
void readCurrentThroughContactors_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define isContactorSet_ExpectAndReturn(pin, port, current_multiplier, cmock_retval) isContactorSet_CMockExpectAndReturn(__LINE__, pin, port, current_multiplier, cmock_retval)
void isContactorSet_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t pin, GPIO_TypeDef* port, int current_multiplier, int cmock_to_return);
#define resetSenseArray_Expect(senses) resetSenseArray_CMockExpect(__LINE__, senses)
void resetSenseArray_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t* senses);
#define isSenseStable_ExpectAndReturn(senses, cmock_retval) isSenseStable_CMockExpectAndReturn(__LINE__, senses, cmock_retval)
void isSenseStable_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t* senses, int cmock_to_return);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
