/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSETCONTACTORSTASK_H
#define _MOCKSETCONTACTORSTASK_H

#include "unity.h"
#include "SetContactorsTask.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void MockSetContactorsTask_Init(void);
void MockSetContactorsTask_Destroy(void);
void MockSetContactorsTask_Verify(void);




#define setContactorsTask_Expect(arg) setContactorsTask_CMockExpect(__LINE__, arg)
void setContactorsTask_CMockExpect(UNITY_LINE_TYPE cmock_line, void const* arg);
#define disconnectContactors_Expect(isContactorError) disconnectContactors_CMockExpect(__LINE__, isContactorError)
void disconnectContactors_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t isContactorError);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
