/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKCHECKCURRENT_H
#define _MOCKCHECKCURRENT_H

#include "unity.h"
#include "CheckCurrent.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void MockCheckCurrent_Init(void);
void MockCheckCurrent_Destroy(void);
void MockCheckCurrent_Verify(void);




#define isCurrentLow_ExpectAndReturn(numContactorsClosed, cmock_retval) isCurrentLow_CMockExpectAndReturn(__LINE__, numContactorsClosed, cmock_retval)
void isCurrentLow_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t numContactorsClosed, uint8_t cmock_to_return);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
