/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockstm32f4xx_hal_spi.h"

static const char* CMockString_CallbackID = "CallbackID";
static const char* CMockString_HAL_SPI_Abort = "HAL_SPI_Abort";
static const char* CMockString_HAL_SPI_AbortCpltCallback = "HAL_SPI_AbortCpltCallback";
static const char* CMockString_HAL_SPI_Abort_IT = "HAL_SPI_Abort_IT";
static const char* CMockString_HAL_SPI_DMAPause = "HAL_SPI_DMAPause";
static const char* CMockString_HAL_SPI_DMAResume = "HAL_SPI_DMAResume";
static const char* CMockString_HAL_SPI_DMAStop = "HAL_SPI_DMAStop";
static const char* CMockString_HAL_SPI_DeInit = "HAL_SPI_DeInit";
static const char* CMockString_HAL_SPI_ErrorCallback = "HAL_SPI_ErrorCallback";
static const char* CMockString_HAL_SPI_GetError = "HAL_SPI_GetError";
static const char* CMockString_HAL_SPI_GetState = "HAL_SPI_GetState";
static const char* CMockString_HAL_SPI_IRQHandler = "HAL_SPI_IRQHandler";
static const char* CMockString_HAL_SPI_Init = "HAL_SPI_Init";
static const char* CMockString_HAL_SPI_MspDeInit = "HAL_SPI_MspDeInit";
static const char* CMockString_HAL_SPI_MspInit = "HAL_SPI_MspInit";
static const char* CMockString_HAL_SPI_Receive = "HAL_SPI_Receive";
static const char* CMockString_HAL_SPI_Receive_DMA = "HAL_SPI_Receive_DMA";
static const char* CMockString_HAL_SPI_Receive_IT = "HAL_SPI_Receive_IT";
static const char* CMockString_HAL_SPI_RegisterCallback = "HAL_SPI_RegisterCallback";
static const char* CMockString_HAL_SPI_RxCpltCallback = "HAL_SPI_RxCpltCallback";
static const char* CMockString_HAL_SPI_RxHalfCpltCallback = "HAL_SPI_RxHalfCpltCallback";
static const char* CMockString_HAL_SPI_Transmit = "HAL_SPI_Transmit";
static const char* CMockString_HAL_SPI_TransmitReceive = "HAL_SPI_TransmitReceive";
static const char* CMockString_HAL_SPI_TransmitReceive_DMA = "HAL_SPI_TransmitReceive_DMA";
static const char* CMockString_HAL_SPI_TransmitReceive_IT = "HAL_SPI_TransmitReceive_IT";
static const char* CMockString_HAL_SPI_Transmit_DMA = "HAL_SPI_Transmit_DMA";
static const char* CMockString_HAL_SPI_Transmit_IT = "HAL_SPI_Transmit_IT";
static const char* CMockString_HAL_SPI_TxCpltCallback = "HAL_SPI_TxCpltCallback";
static const char* CMockString_HAL_SPI_TxHalfCpltCallback = "HAL_SPI_TxHalfCpltCallback";
static const char* CMockString_HAL_SPI_TxRxCpltCallback = "HAL_SPI_TxRxCpltCallback";
static const char* CMockString_HAL_SPI_TxRxHalfCpltCallback = "HAL_SPI_TxRxHalfCpltCallback";
static const char* CMockString_HAL_SPI_UnRegisterCallback = "HAL_SPI_UnRegisterCallback";
static const char* CMockString_Size = "Size";
static const char* CMockString_Timeout = "Timeout";
static const char* CMockString_hspi = "hspi";
static const char* CMockString_pCallback = "pCallback";
static const char* CMockString_pData = "pData";
static const char* CMockString_pRxData = "pRxData";
static const char* CMockString_pTxData = "pTxData";

typedef struct _CMOCK_HAL_SPI_Init_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    HAL_StatusTypeDef ReturnVal;
    SPI_HandleTypeDef* Expected_hspi;

} CMOCK_HAL_SPI_Init_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_DeInit_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    HAL_StatusTypeDef ReturnVal;
    SPI_HandleTypeDef* Expected_hspi;

} CMOCK_HAL_SPI_DeInit_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_MspInit_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    SPI_HandleTypeDef* Expected_hspi;

} CMOCK_HAL_SPI_MspInit_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_MspDeInit_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    SPI_HandleTypeDef* Expected_hspi;

} CMOCK_HAL_SPI_MspDeInit_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_RegisterCallback_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    HAL_StatusTypeDef ReturnVal;
    SPI_HandleTypeDef* Expected_hspi;
    HAL_SPI_CallbackIDTypeDef Expected_CallbackID;
    pSPI_CallbackTypeDef Expected_pCallback;

} CMOCK_HAL_SPI_RegisterCallback_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_UnRegisterCallback_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    HAL_StatusTypeDef ReturnVal;
    SPI_HandleTypeDef* Expected_hspi;
    HAL_SPI_CallbackIDTypeDef Expected_CallbackID;

} CMOCK_HAL_SPI_UnRegisterCallback_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_Transmit_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    HAL_StatusTypeDef ReturnVal;
    SPI_HandleTypeDef* Expected_hspi;
    uint8_t* Expected_pData;
    uint16_t Expected_Size;
    uint32_t Expected_Timeout;

} CMOCK_HAL_SPI_Transmit_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_Receive_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    HAL_StatusTypeDef ReturnVal;
    SPI_HandleTypeDef* Expected_hspi;
    uint8_t* Expected_pData;
    uint16_t Expected_Size;
    uint32_t Expected_Timeout;

} CMOCK_HAL_SPI_Receive_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_TransmitReceive_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    HAL_StatusTypeDef ReturnVal;
    SPI_HandleTypeDef* Expected_hspi;
    uint8_t* Expected_pTxData;
    uint8_t* Expected_pRxData;
    uint16_t Expected_Size;
    uint32_t Expected_Timeout;

} CMOCK_HAL_SPI_TransmitReceive_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_Transmit_IT_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    HAL_StatusTypeDef ReturnVal;
    SPI_HandleTypeDef* Expected_hspi;
    uint8_t* Expected_pData;
    uint16_t Expected_Size;

} CMOCK_HAL_SPI_Transmit_IT_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_Receive_IT_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    HAL_StatusTypeDef ReturnVal;
    SPI_HandleTypeDef* Expected_hspi;
    uint8_t* Expected_pData;
    uint16_t Expected_Size;

} CMOCK_HAL_SPI_Receive_IT_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_TransmitReceive_IT_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    HAL_StatusTypeDef ReturnVal;
    SPI_HandleTypeDef* Expected_hspi;
    uint8_t* Expected_pTxData;
    uint8_t* Expected_pRxData;
    uint16_t Expected_Size;

} CMOCK_HAL_SPI_TransmitReceive_IT_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_Transmit_DMA_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    HAL_StatusTypeDef ReturnVal;
    SPI_HandleTypeDef* Expected_hspi;
    uint8_t* Expected_pData;
    uint16_t Expected_Size;

} CMOCK_HAL_SPI_Transmit_DMA_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_Receive_DMA_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    HAL_StatusTypeDef ReturnVal;
    SPI_HandleTypeDef* Expected_hspi;
    uint8_t* Expected_pData;
    uint16_t Expected_Size;

} CMOCK_HAL_SPI_Receive_DMA_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_TransmitReceive_DMA_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    HAL_StatusTypeDef ReturnVal;
    SPI_HandleTypeDef* Expected_hspi;
    uint8_t* Expected_pTxData;
    uint8_t* Expected_pRxData;
    uint16_t Expected_Size;

} CMOCK_HAL_SPI_TransmitReceive_DMA_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_DMAPause_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    HAL_StatusTypeDef ReturnVal;
    SPI_HandleTypeDef* Expected_hspi;

} CMOCK_HAL_SPI_DMAPause_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_DMAResume_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    HAL_StatusTypeDef ReturnVal;
    SPI_HandleTypeDef* Expected_hspi;

} CMOCK_HAL_SPI_DMAResume_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_DMAStop_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    HAL_StatusTypeDef ReturnVal;
    SPI_HandleTypeDef* Expected_hspi;

} CMOCK_HAL_SPI_DMAStop_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_Abort_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    HAL_StatusTypeDef ReturnVal;
    SPI_HandleTypeDef* Expected_hspi;

} CMOCK_HAL_SPI_Abort_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_Abort_IT_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    HAL_StatusTypeDef ReturnVal;
    SPI_HandleTypeDef* Expected_hspi;

} CMOCK_HAL_SPI_Abort_IT_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_IRQHandler_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    SPI_HandleTypeDef* Expected_hspi;

} CMOCK_HAL_SPI_IRQHandler_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_TxCpltCallback_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    SPI_HandleTypeDef* Expected_hspi;

} CMOCK_HAL_SPI_TxCpltCallback_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_RxCpltCallback_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    SPI_HandleTypeDef* Expected_hspi;

} CMOCK_HAL_SPI_RxCpltCallback_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_TxRxCpltCallback_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    SPI_HandleTypeDef* Expected_hspi;

} CMOCK_HAL_SPI_TxRxCpltCallback_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_TxHalfCpltCallback_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    SPI_HandleTypeDef* Expected_hspi;

} CMOCK_HAL_SPI_TxHalfCpltCallback_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_RxHalfCpltCallback_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    SPI_HandleTypeDef* Expected_hspi;

} CMOCK_HAL_SPI_RxHalfCpltCallback_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_TxRxHalfCpltCallback_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    SPI_HandleTypeDef* Expected_hspi;

} CMOCK_HAL_SPI_TxRxHalfCpltCallback_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_ErrorCallback_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    SPI_HandleTypeDef* Expected_hspi;

} CMOCK_HAL_SPI_ErrorCallback_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_AbortCpltCallback_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    SPI_HandleTypeDef* Expected_hspi;

} CMOCK_HAL_SPI_AbortCpltCallback_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_GetState_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    HAL_SPI_StateTypeDef ReturnVal;
    SPI_HandleTypeDef* Expected_hspi;

} CMOCK_HAL_SPI_GetState_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SPI_GetError_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    uint32_t ReturnVal;
    SPI_HandleTypeDef* Expected_hspi;

} CMOCK_HAL_SPI_GetError_CALL_INSTANCE;

static struct Mockstm32f4xx_hal_spiInstance
{
    CMOCK_MEM_INDEX_TYPE HAL_SPI_Init_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_DeInit_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_MspInit_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_MspDeInit_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_RegisterCallback_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_UnRegisterCallback_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_Transmit_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_Receive_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_TransmitReceive_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_Transmit_IT_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_Receive_IT_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_TransmitReceive_IT_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_Transmit_DMA_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_Receive_DMA_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_TransmitReceive_DMA_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_DMAPause_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_DMAResume_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_DMAStop_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_Abort_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_Abort_IT_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_IRQHandler_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_TxCpltCallback_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_RxCpltCallback_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_TxRxCpltCallback_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_TxHalfCpltCallback_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_RxHalfCpltCallback_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_TxRxHalfCpltCallback_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_ErrorCallback_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_AbortCpltCallback_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_GetState_CallInstance;
    CMOCK_MEM_INDEX_TYPE HAL_SPI_GetError_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockstm32f4xx_hal_spi_Verify(void)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_MEM_INDEX_TYPE call_instance;
    call_instance = Mock.HAL_SPI_Init_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_Init);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_DeInit_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_DeInit);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_MspInit_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_MspInit);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_MspDeInit_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_MspDeInit);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_RegisterCallback_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_RegisterCallback);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_UnRegisterCallback_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_UnRegisterCallback);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_Transmit_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_Transmit);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_Receive_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_Receive);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_TransmitReceive_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_TransmitReceive);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_Transmit_IT_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_Transmit_IT);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_Receive_IT_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_Receive_IT);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_TransmitReceive_IT_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_TransmitReceive_IT);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_Transmit_DMA_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_Transmit_DMA);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_Receive_DMA_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_Receive_DMA);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_TransmitReceive_DMA_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_TransmitReceive_DMA);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_DMAPause_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_DMAPause);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_DMAResume_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_DMAResume);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_DMAStop_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_DMAStop);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_Abort_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_Abort);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_Abort_IT_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_Abort_IT);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_IRQHandler_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_IRQHandler);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_TxCpltCallback_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_TxCpltCallback);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_RxCpltCallback_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_RxCpltCallback);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_TxRxCpltCallback_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_TxRxCpltCallback);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_TxHalfCpltCallback_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_TxHalfCpltCallback);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_RxHalfCpltCallback_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_RxHalfCpltCallback);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_TxRxHalfCpltCallback_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_TxRxHalfCpltCallback);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_ErrorCallback_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_ErrorCallback);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_AbortCpltCallback_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_AbortCpltCallback);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_GetState_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_GetState);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }

    call_instance = Mock.HAL_SPI_GetError_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_HAL_SPI_GetError);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }
}

void Mockstm32f4xx_hal_spi_Init(void)
{
    Mockstm32f4xx_hal_spi_Destroy();
}

void Mockstm32f4xx_hal_spi_Destroy(void)
{
    CMock_Guts_MemFreeAll();
    memset(&Mock, 0, sizeof(Mock));
}

HAL_StatusTypeDef HAL_SPI_Init(SPI_HandleTypeDef* hspi)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_Init_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_Init);
    cmock_call_instance = (CMOCK_HAL_SPI_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_Init_CallInstance);
    Mock.HAL_SPI_Init_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_Init_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_Init, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_SPI_Init(CMOCK_HAL_SPI_Init_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi)
{
    cmock_call_instance->Expected_hspi = hspi;
}

void HAL_SPI_Init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, HAL_StatusTypeDef cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_Init_CALL_INSTANCE));
    CMOCK_HAL_SPI_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_Init_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_Init_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_Init(cmock_call_instance, hspi);
    memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
           sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_SPI_DeInit(SPI_HandleTypeDef* hspi)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_DeInit_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_DeInit);
    cmock_call_instance = (CMOCK_HAL_SPI_DeInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_DeInit_CallInstance);
    Mock.HAL_SPI_DeInit_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_DeInit_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_DeInit, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_SPI_DeInit(CMOCK_HAL_SPI_DeInit_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi)
{
    cmock_call_instance->Expected_hspi = hspi;
}

void HAL_SPI_DeInit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, HAL_StatusTypeDef cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_DeInit_CALL_INSTANCE));
    CMOCK_HAL_SPI_DeInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_DeInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_DeInit_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_DeInit_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_DeInit(cmock_call_instance, hspi);
    memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
           sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

void HAL_SPI_MspInit(SPI_HandleTypeDef* hspi)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_MspInit_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_MspInit);
    cmock_call_instance = (CMOCK_HAL_SPI_MspInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_MspInit_CallInstance);
    Mock.HAL_SPI_MspInit_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_MspInit_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_MspInit, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_SPI_MspInit(CMOCK_HAL_SPI_MspInit_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi)
{
    cmock_call_instance->Expected_hspi = hspi;
}

void HAL_SPI_MspInit_CMockExpect(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_MspInit_CALL_INSTANCE));
    CMOCK_HAL_SPI_MspInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_MspInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_MspInit_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_MspInit_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_MspInit(cmock_call_instance, hspi);
}

void HAL_SPI_MspDeInit(SPI_HandleTypeDef* hspi)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_MspDeInit_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_MspDeInit);
    cmock_call_instance = (CMOCK_HAL_SPI_MspDeInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_MspDeInit_CallInstance);
    Mock.HAL_SPI_MspDeInit_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_MspDeInit_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_MspDeInit, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_SPI_MspDeInit(CMOCK_HAL_SPI_MspDeInit_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi)
{
    cmock_call_instance->Expected_hspi = hspi;
}

void HAL_SPI_MspDeInit_CMockExpect(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_MspDeInit_CALL_INSTANCE));
    CMOCK_HAL_SPI_MspDeInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_MspDeInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_MspDeInit_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_MspDeInit_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_MspDeInit(cmock_call_instance, hspi);
}

HAL_StatusTypeDef HAL_SPI_RegisterCallback(SPI_HandleTypeDef* hspi, HAL_SPI_CallbackIDTypeDef CallbackID, pSPI_CallbackTypeDef pCallback)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_RegisterCallback_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_RegisterCallback);
    cmock_call_instance = (CMOCK_HAL_SPI_RegisterCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_RegisterCallback_CallInstance);
    Mock.HAL_SPI_RegisterCallback_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_RegisterCallback_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_RegisterCallback, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_RegisterCallback, CMockString_CallbackID);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_CallbackID), (void*)(&CallbackID), sizeof(HAL_SPI_CallbackIDTypeDef), cmock_line, CMockStringMismatch);
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_RegisterCallback, CMockString_pCallback);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_pCallback), (void*)(&pCallback), sizeof(pSPI_CallbackTypeDef), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_SPI_RegisterCallback(CMOCK_HAL_SPI_RegisterCallback_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi, HAL_SPI_CallbackIDTypeDef CallbackID, pSPI_CallbackTypeDef pCallback)
{
    cmock_call_instance->Expected_hspi = hspi;
    memcpy((void*)(&cmock_call_instance->Expected_CallbackID), (void*)(&CallbackID),
           sizeof(HAL_SPI_CallbackIDTypeDef[sizeof(CallbackID) == sizeof(HAL_SPI_CallbackIDTypeDef) ? 1 : -1])); /* add HAL_SPI_CallbackIDTypeDef to :treat_as_array if this causes an error */
    memcpy((void*)(&cmock_call_instance->Expected_pCallback), (void*)(&pCallback),
           sizeof(pSPI_CallbackTypeDef[sizeof(pCallback) == sizeof(pSPI_CallbackTypeDef) ? 1 : -1])); /* add pSPI_CallbackTypeDef to :treat_as_array if this causes an error */
}

void HAL_SPI_RegisterCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, HAL_SPI_CallbackIDTypeDef CallbackID, pSPI_CallbackTypeDef pCallback, HAL_StatusTypeDef cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_RegisterCallback_CALL_INSTANCE));
    CMOCK_HAL_SPI_RegisterCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_RegisterCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_RegisterCallback_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_RegisterCallback_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_RegisterCallback(cmock_call_instance, hspi, CallbackID, pCallback);
    memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
           sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_SPI_UnRegisterCallback(SPI_HandleTypeDef* hspi, HAL_SPI_CallbackIDTypeDef CallbackID)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_UnRegisterCallback_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_UnRegisterCallback);
    cmock_call_instance = (CMOCK_HAL_SPI_UnRegisterCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_UnRegisterCallback_CallInstance);
    Mock.HAL_SPI_UnRegisterCallback_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_UnRegisterCallback_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_UnRegisterCallback, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_UnRegisterCallback, CMockString_CallbackID);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_CallbackID), (void*)(&CallbackID), sizeof(HAL_SPI_CallbackIDTypeDef), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_SPI_UnRegisterCallback(CMOCK_HAL_SPI_UnRegisterCallback_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi, HAL_SPI_CallbackIDTypeDef CallbackID)
{
    cmock_call_instance->Expected_hspi = hspi;
    memcpy((void*)(&cmock_call_instance->Expected_CallbackID), (void*)(&CallbackID),
           sizeof(HAL_SPI_CallbackIDTypeDef[sizeof(CallbackID) == sizeof(HAL_SPI_CallbackIDTypeDef) ? 1 : -1])); /* add HAL_SPI_CallbackIDTypeDef to :treat_as_array if this causes an error */
}

void HAL_SPI_UnRegisterCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, HAL_SPI_CallbackIDTypeDef CallbackID, HAL_StatusTypeDef cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_UnRegisterCallback_CALL_INSTANCE));
    CMOCK_HAL_SPI_UnRegisterCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_UnRegisterCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_UnRegisterCallback_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_UnRegisterCallback_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_UnRegisterCallback(cmock_call_instance, hspi, CallbackID);
    memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
           sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_SPI_Transmit(SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size, uint32_t Timeout)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_Transmit_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_Transmit);
    cmock_call_instance = (CMOCK_HAL_SPI_Transmit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_Transmit_CallInstance);
    Mock.HAL_SPI_Transmit_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_Transmit_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_Transmit, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_Transmit, CMockString_pData);

        if (cmock_call_instance->Expected_pData == NULL)
        {
            UNITY_TEST_ASSERT_NULL(pData, cmock_line, CMockStringExpNULL);
        }
        else
        {
            UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_pData, pData, 1, cmock_line, CMockStringMismatch);
        }
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_Transmit, CMockString_Size);
        UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_Size, Size, cmock_line, CMockStringMismatch);
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_Transmit, CMockString_Timeout);
        UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_Timeout, Timeout, cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_SPI_Transmit(CMOCK_HAL_SPI_Transmit_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size, uint32_t Timeout)
{
    cmock_call_instance->Expected_hspi = hspi;
    cmock_call_instance->Expected_pData = pData;
    cmock_call_instance->Expected_Size = Size;
    cmock_call_instance->Expected_Timeout = Timeout;
}

void HAL_SPI_Transmit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_Transmit_CALL_INSTANCE));
    CMOCK_HAL_SPI_Transmit_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_Transmit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_Transmit_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_Transmit_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_Transmit(cmock_call_instance, hspi, pData, Size, Timeout);
    memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
           sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_SPI_Receive(SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size, uint32_t Timeout)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_Receive_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_Receive);
    cmock_call_instance = (CMOCK_HAL_SPI_Receive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_Receive_CallInstance);
    Mock.HAL_SPI_Receive_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_Receive_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_Receive, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_Receive, CMockString_pData);

        if (cmock_call_instance->Expected_pData == NULL)
        {
            UNITY_TEST_ASSERT_NULL(pData, cmock_line, CMockStringExpNULL);
        }
        else
        {
            UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_pData, pData, 1, cmock_line, CMockStringMismatch);
        }
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_Receive, CMockString_Size);
        UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_Size, Size, cmock_line, CMockStringMismatch);
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_Receive, CMockString_Timeout);
        UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_Timeout, Timeout, cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_SPI_Receive(CMOCK_HAL_SPI_Receive_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size, uint32_t Timeout)
{
    cmock_call_instance->Expected_hspi = hspi;
    cmock_call_instance->Expected_pData = pData;
    cmock_call_instance->Expected_Size = Size;
    cmock_call_instance->Expected_Timeout = Timeout;
}

void HAL_SPI_Receive_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_Receive_CALL_INSTANCE));
    CMOCK_HAL_SPI_Receive_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_Receive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_Receive_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_Receive_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_Receive(cmock_call_instance, hspi, pData, Size, Timeout);
    memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
           sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_SPI_TransmitReceive(SPI_HandleTypeDef* hspi, uint8_t* pTxData, uint8_t* pRxData, uint16_t Size, uint32_t Timeout)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_TransmitReceive_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_TransmitReceive);
    cmock_call_instance = (CMOCK_HAL_SPI_TransmitReceive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_TransmitReceive_CallInstance);
    Mock.HAL_SPI_TransmitReceive_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_TransmitReceive_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_TransmitReceive, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_TransmitReceive, CMockString_pTxData);

        if (cmock_call_instance->Expected_pTxData == NULL)
        {
            UNITY_TEST_ASSERT_NULL(pTxData, cmock_line, CMockStringExpNULL);
        }
        else
        {
            UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_pTxData, pTxData, 1, cmock_line, CMockStringMismatch);
        }
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_TransmitReceive, CMockString_pRxData);

        if (cmock_call_instance->Expected_pRxData == NULL)
        {
            UNITY_TEST_ASSERT_NULL(pRxData, cmock_line, CMockStringExpNULL);
        }
        else
        {
            UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_pRxData, pRxData, 1, cmock_line, CMockStringMismatch);
        }
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_TransmitReceive, CMockString_Size);
        UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_Size, Size, cmock_line, CMockStringMismatch);
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_TransmitReceive, CMockString_Timeout);
        UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_Timeout, Timeout, cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_SPI_TransmitReceive(CMOCK_HAL_SPI_TransmitReceive_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi, uint8_t* pTxData, uint8_t* pRxData, uint16_t Size, uint32_t Timeout)
{
    cmock_call_instance->Expected_hspi = hspi;
    cmock_call_instance->Expected_pTxData = pTxData;
    cmock_call_instance->Expected_pRxData = pRxData;
    cmock_call_instance->Expected_Size = Size;
    cmock_call_instance->Expected_Timeout = Timeout;
}

void HAL_SPI_TransmitReceive_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, uint8_t* pTxData, uint8_t* pRxData, uint16_t Size, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_TransmitReceive_CALL_INSTANCE));
    CMOCK_HAL_SPI_TransmitReceive_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_TransmitReceive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_TransmitReceive_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_TransmitReceive_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_TransmitReceive(cmock_call_instance, hspi, pTxData, pRxData, Size, Timeout);
    memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
           sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_SPI_Transmit_IT(SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_Transmit_IT_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_Transmit_IT);
    cmock_call_instance = (CMOCK_HAL_SPI_Transmit_IT_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_Transmit_IT_CallInstance);
    Mock.HAL_SPI_Transmit_IT_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_Transmit_IT_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_Transmit_IT, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_Transmit_IT, CMockString_pData);

        if (cmock_call_instance->Expected_pData == NULL)
        {
            UNITY_TEST_ASSERT_NULL(pData, cmock_line, CMockStringExpNULL);
        }
        else
        {
            UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_pData, pData, 1, cmock_line, CMockStringMismatch);
        }
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_Transmit_IT, CMockString_Size);
        UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_Size, Size, cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_SPI_Transmit_IT(CMOCK_HAL_SPI_Transmit_IT_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size)
{
    cmock_call_instance->Expected_hspi = hspi;
    cmock_call_instance->Expected_pData = pData;
    cmock_call_instance->Expected_Size = Size;
}

void HAL_SPI_Transmit_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_Transmit_IT_CALL_INSTANCE));
    CMOCK_HAL_SPI_Transmit_IT_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_Transmit_IT_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_Transmit_IT_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_Transmit_IT_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_Transmit_IT(cmock_call_instance, hspi, pData, Size);
    memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
           sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_SPI_Receive_IT(SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_Receive_IT_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_Receive_IT);
    cmock_call_instance = (CMOCK_HAL_SPI_Receive_IT_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_Receive_IT_CallInstance);
    Mock.HAL_SPI_Receive_IT_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_Receive_IT_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_Receive_IT, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_Receive_IT, CMockString_pData);

        if (cmock_call_instance->Expected_pData == NULL)
        {
            UNITY_TEST_ASSERT_NULL(pData, cmock_line, CMockStringExpNULL);
        }
        else
        {
            UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_pData, pData, 1, cmock_line, CMockStringMismatch);
        }
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_Receive_IT, CMockString_Size);
        UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_Size, Size, cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_SPI_Receive_IT(CMOCK_HAL_SPI_Receive_IT_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size)
{
    cmock_call_instance->Expected_hspi = hspi;
    cmock_call_instance->Expected_pData = pData;
    cmock_call_instance->Expected_Size = Size;
}

void HAL_SPI_Receive_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_Receive_IT_CALL_INSTANCE));
    CMOCK_HAL_SPI_Receive_IT_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_Receive_IT_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_Receive_IT_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_Receive_IT_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_Receive_IT(cmock_call_instance, hspi, pData, Size);
    memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
           sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_SPI_TransmitReceive_IT(SPI_HandleTypeDef* hspi, uint8_t* pTxData, uint8_t* pRxData, uint16_t Size)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_TransmitReceive_IT_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_TransmitReceive_IT);
    cmock_call_instance = (CMOCK_HAL_SPI_TransmitReceive_IT_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_TransmitReceive_IT_CallInstance);
    Mock.HAL_SPI_TransmitReceive_IT_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_TransmitReceive_IT_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_TransmitReceive_IT, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_TransmitReceive_IT, CMockString_pTxData);

        if (cmock_call_instance->Expected_pTxData == NULL)
        {
            UNITY_TEST_ASSERT_NULL(pTxData, cmock_line, CMockStringExpNULL);
        }
        else
        {
            UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_pTxData, pTxData, 1, cmock_line, CMockStringMismatch);
        }
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_TransmitReceive_IT, CMockString_pRxData);

        if (cmock_call_instance->Expected_pRxData == NULL)
        {
            UNITY_TEST_ASSERT_NULL(pRxData, cmock_line, CMockStringExpNULL);
        }
        else
        {
            UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_pRxData, pRxData, 1, cmock_line, CMockStringMismatch);
        }
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_TransmitReceive_IT, CMockString_Size);
        UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_Size, Size, cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_SPI_TransmitReceive_IT(CMOCK_HAL_SPI_TransmitReceive_IT_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi, uint8_t* pTxData, uint8_t* pRxData, uint16_t Size)
{
    cmock_call_instance->Expected_hspi = hspi;
    cmock_call_instance->Expected_pTxData = pTxData;
    cmock_call_instance->Expected_pRxData = pRxData;
    cmock_call_instance->Expected_Size = Size;
}

void HAL_SPI_TransmitReceive_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, uint8_t* pTxData, uint8_t* pRxData, uint16_t Size, HAL_StatusTypeDef cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_TransmitReceive_IT_CALL_INSTANCE));
    CMOCK_HAL_SPI_TransmitReceive_IT_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_TransmitReceive_IT_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_TransmitReceive_IT_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_TransmitReceive_IT_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_TransmitReceive_IT(cmock_call_instance, hspi, pTxData, pRxData, Size);
    memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
           sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_SPI_Transmit_DMA(SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_Transmit_DMA_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_Transmit_DMA);
    cmock_call_instance = (CMOCK_HAL_SPI_Transmit_DMA_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_Transmit_DMA_CallInstance);
    Mock.HAL_SPI_Transmit_DMA_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_Transmit_DMA_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_Transmit_DMA, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_Transmit_DMA, CMockString_pData);

        if (cmock_call_instance->Expected_pData == NULL)
        {
            UNITY_TEST_ASSERT_NULL(pData, cmock_line, CMockStringExpNULL);
        }
        else
        {
            UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_pData, pData, 1, cmock_line, CMockStringMismatch);
        }
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_Transmit_DMA, CMockString_Size);
        UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_Size, Size, cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_SPI_Transmit_DMA(CMOCK_HAL_SPI_Transmit_DMA_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size)
{
    cmock_call_instance->Expected_hspi = hspi;
    cmock_call_instance->Expected_pData = pData;
    cmock_call_instance->Expected_Size = Size;
}

void HAL_SPI_Transmit_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_Transmit_DMA_CALL_INSTANCE));
    CMOCK_HAL_SPI_Transmit_DMA_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_Transmit_DMA_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_Transmit_DMA_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_Transmit_DMA_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_Transmit_DMA(cmock_call_instance, hspi, pData, Size);
    memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
           sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_SPI_Receive_DMA(SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_Receive_DMA_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_Receive_DMA);
    cmock_call_instance = (CMOCK_HAL_SPI_Receive_DMA_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_Receive_DMA_CallInstance);
    Mock.HAL_SPI_Receive_DMA_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_Receive_DMA_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_Receive_DMA, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_Receive_DMA, CMockString_pData);

        if (cmock_call_instance->Expected_pData == NULL)
        {
            UNITY_TEST_ASSERT_NULL(pData, cmock_line, CMockStringExpNULL);
        }
        else
        {
            UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_pData, pData, 1, cmock_line, CMockStringMismatch);
        }
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_Receive_DMA, CMockString_Size);
        UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_Size, Size, cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_SPI_Receive_DMA(CMOCK_HAL_SPI_Receive_DMA_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size)
{
    cmock_call_instance->Expected_hspi = hspi;
    cmock_call_instance->Expected_pData = pData;
    cmock_call_instance->Expected_Size = Size;
}

void HAL_SPI_Receive_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_Receive_DMA_CALL_INSTANCE));
    CMOCK_HAL_SPI_Receive_DMA_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_Receive_DMA_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_Receive_DMA_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_Receive_DMA_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_Receive_DMA(cmock_call_instance, hspi, pData, Size);
    memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
           sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_SPI_TransmitReceive_DMA(SPI_HandleTypeDef* hspi, uint8_t* pTxData, uint8_t* pRxData, uint16_t Size)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_TransmitReceive_DMA_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_TransmitReceive_DMA);
    cmock_call_instance = (CMOCK_HAL_SPI_TransmitReceive_DMA_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_TransmitReceive_DMA_CallInstance);
    Mock.HAL_SPI_TransmitReceive_DMA_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_TransmitReceive_DMA_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_TransmitReceive_DMA, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_TransmitReceive_DMA, CMockString_pTxData);

        if (cmock_call_instance->Expected_pTxData == NULL)
        {
            UNITY_TEST_ASSERT_NULL(pTxData, cmock_line, CMockStringExpNULL);
        }
        else
        {
            UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_pTxData, pTxData, 1, cmock_line, CMockStringMismatch);
        }
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_TransmitReceive_DMA, CMockString_pRxData);

        if (cmock_call_instance->Expected_pRxData == NULL)
        {
            UNITY_TEST_ASSERT_NULL(pRxData, cmock_line, CMockStringExpNULL);
        }
        else
        {
            UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_pRxData, pRxData, 1, cmock_line, CMockStringMismatch);
        }
    }
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_TransmitReceive_DMA, CMockString_Size);
        UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_Size, Size, cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_SPI_TransmitReceive_DMA(CMOCK_HAL_SPI_TransmitReceive_DMA_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi, uint8_t* pTxData, uint8_t* pRxData, uint16_t Size)
{
    cmock_call_instance->Expected_hspi = hspi;
    cmock_call_instance->Expected_pTxData = pTxData;
    cmock_call_instance->Expected_pRxData = pRxData;
    cmock_call_instance->Expected_Size = Size;
}

void HAL_SPI_TransmitReceive_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, uint8_t* pTxData, uint8_t* pRxData, uint16_t Size, HAL_StatusTypeDef cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_TransmitReceive_DMA_CALL_INSTANCE));
    CMOCK_HAL_SPI_TransmitReceive_DMA_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_TransmitReceive_DMA_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_TransmitReceive_DMA_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_TransmitReceive_DMA_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_TransmitReceive_DMA(cmock_call_instance, hspi, pTxData, pRxData, Size);
    memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
           sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_SPI_DMAPause(SPI_HandleTypeDef* hspi)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_DMAPause_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_DMAPause);
    cmock_call_instance = (CMOCK_HAL_SPI_DMAPause_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_DMAPause_CallInstance);
    Mock.HAL_SPI_DMAPause_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_DMAPause_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_DMAPause, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_SPI_DMAPause(CMOCK_HAL_SPI_DMAPause_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi)
{
    cmock_call_instance->Expected_hspi = hspi;
}

void HAL_SPI_DMAPause_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, HAL_StatusTypeDef cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_DMAPause_CALL_INSTANCE));
    CMOCK_HAL_SPI_DMAPause_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_DMAPause_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_DMAPause_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_DMAPause_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_DMAPause(cmock_call_instance, hspi);
    memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
           sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_SPI_DMAResume(SPI_HandleTypeDef* hspi)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_DMAResume_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_DMAResume);
    cmock_call_instance = (CMOCK_HAL_SPI_DMAResume_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_DMAResume_CallInstance);
    Mock.HAL_SPI_DMAResume_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_DMAResume_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_DMAResume, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_SPI_DMAResume(CMOCK_HAL_SPI_DMAResume_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi)
{
    cmock_call_instance->Expected_hspi = hspi;
}

void HAL_SPI_DMAResume_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, HAL_StatusTypeDef cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_DMAResume_CALL_INSTANCE));
    CMOCK_HAL_SPI_DMAResume_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_DMAResume_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_DMAResume_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_DMAResume_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_DMAResume(cmock_call_instance, hspi);
    memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
           sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_SPI_DMAStop(SPI_HandleTypeDef* hspi)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_DMAStop_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_DMAStop);
    cmock_call_instance = (CMOCK_HAL_SPI_DMAStop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_DMAStop_CallInstance);
    Mock.HAL_SPI_DMAStop_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_DMAStop_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_DMAStop, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_SPI_DMAStop(CMOCK_HAL_SPI_DMAStop_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi)
{
    cmock_call_instance->Expected_hspi = hspi;
}

void HAL_SPI_DMAStop_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, HAL_StatusTypeDef cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_DMAStop_CALL_INSTANCE));
    CMOCK_HAL_SPI_DMAStop_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_DMAStop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_DMAStop_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_DMAStop_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_DMAStop(cmock_call_instance, hspi);
    memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
           sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_SPI_Abort(SPI_HandleTypeDef* hspi)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_Abort_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_Abort);
    cmock_call_instance = (CMOCK_HAL_SPI_Abort_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_Abort_CallInstance);
    Mock.HAL_SPI_Abort_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_Abort_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_Abort, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_SPI_Abort(CMOCK_HAL_SPI_Abort_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi)
{
    cmock_call_instance->Expected_hspi = hspi;
}

void HAL_SPI_Abort_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, HAL_StatusTypeDef cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_Abort_CALL_INSTANCE));
    CMOCK_HAL_SPI_Abort_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_Abort_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_Abort_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_Abort_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_Abort(cmock_call_instance, hspi);
    memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
           sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_SPI_Abort_IT(SPI_HandleTypeDef* hspi)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_Abort_IT_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_Abort_IT);
    cmock_call_instance = (CMOCK_HAL_SPI_Abort_IT_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_Abort_IT_CallInstance);
    Mock.HAL_SPI_Abort_IT_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_Abort_IT_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_Abort_IT, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_SPI_Abort_IT(CMOCK_HAL_SPI_Abort_IT_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi)
{
    cmock_call_instance->Expected_hspi = hspi;
}

void HAL_SPI_Abort_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, HAL_StatusTypeDef cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_Abort_IT_CALL_INSTANCE));
    CMOCK_HAL_SPI_Abort_IT_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_Abort_IT_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_Abort_IT_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_Abort_IT_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_Abort_IT(cmock_call_instance, hspi);
    memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
           sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

void HAL_SPI_IRQHandler(SPI_HandleTypeDef* hspi)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_IRQHandler_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_IRQHandler);
    cmock_call_instance = (CMOCK_HAL_SPI_IRQHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_IRQHandler_CallInstance);
    Mock.HAL_SPI_IRQHandler_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_IRQHandler_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_IRQHandler, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_SPI_IRQHandler(CMOCK_HAL_SPI_IRQHandler_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi)
{
    cmock_call_instance->Expected_hspi = hspi;
}

void HAL_SPI_IRQHandler_CMockExpect(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_IRQHandler_CALL_INSTANCE));
    CMOCK_HAL_SPI_IRQHandler_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_IRQHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_IRQHandler_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_IRQHandler_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_IRQHandler(cmock_call_instance, hspi);
}

void HAL_SPI_TxCpltCallback(SPI_HandleTypeDef* hspi)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_TxCpltCallback_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_TxCpltCallback);
    cmock_call_instance = (CMOCK_HAL_SPI_TxCpltCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_TxCpltCallback_CallInstance);
    Mock.HAL_SPI_TxCpltCallback_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_TxCpltCallback_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_TxCpltCallback, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_SPI_TxCpltCallback(CMOCK_HAL_SPI_TxCpltCallback_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi)
{
    cmock_call_instance->Expected_hspi = hspi;
}

void HAL_SPI_TxCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_TxCpltCallback_CALL_INSTANCE));
    CMOCK_HAL_SPI_TxCpltCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_TxCpltCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_TxCpltCallback_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_TxCpltCallback_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_TxCpltCallback(cmock_call_instance, hspi);
}

void HAL_SPI_RxCpltCallback(SPI_HandleTypeDef* hspi)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_RxCpltCallback_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_RxCpltCallback);
    cmock_call_instance = (CMOCK_HAL_SPI_RxCpltCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_RxCpltCallback_CallInstance);
    Mock.HAL_SPI_RxCpltCallback_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_RxCpltCallback_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_RxCpltCallback, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_SPI_RxCpltCallback(CMOCK_HAL_SPI_RxCpltCallback_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi)
{
    cmock_call_instance->Expected_hspi = hspi;
}

void HAL_SPI_RxCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_RxCpltCallback_CALL_INSTANCE));
    CMOCK_HAL_SPI_RxCpltCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_RxCpltCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_RxCpltCallback_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_RxCpltCallback_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_RxCpltCallback(cmock_call_instance, hspi);
}

void HAL_SPI_TxRxCpltCallback(SPI_HandleTypeDef* hspi)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_TxRxCpltCallback_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_TxRxCpltCallback);
    cmock_call_instance = (CMOCK_HAL_SPI_TxRxCpltCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_TxRxCpltCallback_CallInstance);
    Mock.HAL_SPI_TxRxCpltCallback_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_TxRxCpltCallback_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_TxRxCpltCallback, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_SPI_TxRxCpltCallback(CMOCK_HAL_SPI_TxRxCpltCallback_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi)
{
    cmock_call_instance->Expected_hspi = hspi;
}

void HAL_SPI_TxRxCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_TxRxCpltCallback_CALL_INSTANCE));
    CMOCK_HAL_SPI_TxRxCpltCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_TxRxCpltCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_TxRxCpltCallback_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_TxRxCpltCallback_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_TxRxCpltCallback(cmock_call_instance, hspi);
}

void HAL_SPI_TxHalfCpltCallback(SPI_HandleTypeDef* hspi)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_TxHalfCpltCallback_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_TxHalfCpltCallback);
    cmock_call_instance = (CMOCK_HAL_SPI_TxHalfCpltCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_TxHalfCpltCallback_CallInstance);
    Mock.HAL_SPI_TxHalfCpltCallback_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_TxHalfCpltCallback_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_TxHalfCpltCallback, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_SPI_TxHalfCpltCallback(CMOCK_HAL_SPI_TxHalfCpltCallback_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi)
{
    cmock_call_instance->Expected_hspi = hspi;
}

void HAL_SPI_TxHalfCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_TxHalfCpltCallback_CALL_INSTANCE));
    CMOCK_HAL_SPI_TxHalfCpltCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_TxHalfCpltCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_TxHalfCpltCallback_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_TxHalfCpltCallback_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_TxHalfCpltCallback(cmock_call_instance, hspi);
}

void HAL_SPI_RxHalfCpltCallback(SPI_HandleTypeDef* hspi)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_RxHalfCpltCallback_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_RxHalfCpltCallback);
    cmock_call_instance = (CMOCK_HAL_SPI_RxHalfCpltCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_RxHalfCpltCallback_CallInstance);
    Mock.HAL_SPI_RxHalfCpltCallback_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_RxHalfCpltCallback_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_RxHalfCpltCallback, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_SPI_RxHalfCpltCallback(CMOCK_HAL_SPI_RxHalfCpltCallback_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi)
{
    cmock_call_instance->Expected_hspi = hspi;
}

void HAL_SPI_RxHalfCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_RxHalfCpltCallback_CALL_INSTANCE));
    CMOCK_HAL_SPI_RxHalfCpltCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_RxHalfCpltCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_RxHalfCpltCallback_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_RxHalfCpltCallback_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_RxHalfCpltCallback(cmock_call_instance, hspi);
}

void HAL_SPI_TxRxHalfCpltCallback(SPI_HandleTypeDef* hspi)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_TxRxHalfCpltCallback_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_TxRxHalfCpltCallback);
    cmock_call_instance = (CMOCK_HAL_SPI_TxRxHalfCpltCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_TxRxHalfCpltCallback_CallInstance);
    Mock.HAL_SPI_TxRxHalfCpltCallback_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_TxRxHalfCpltCallback_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_TxRxHalfCpltCallback, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_SPI_TxRxHalfCpltCallback(CMOCK_HAL_SPI_TxRxHalfCpltCallback_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi)
{
    cmock_call_instance->Expected_hspi = hspi;
}

void HAL_SPI_TxRxHalfCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_TxRxHalfCpltCallback_CALL_INSTANCE));
    CMOCK_HAL_SPI_TxRxHalfCpltCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_TxRxHalfCpltCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_TxRxHalfCpltCallback_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_TxRxHalfCpltCallback_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_TxRxHalfCpltCallback(cmock_call_instance, hspi);
}

void HAL_SPI_ErrorCallback(SPI_HandleTypeDef* hspi)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_ErrorCallback_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_ErrorCallback);
    cmock_call_instance = (CMOCK_HAL_SPI_ErrorCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_ErrorCallback_CallInstance);
    Mock.HAL_SPI_ErrorCallback_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_ErrorCallback_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_ErrorCallback, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_SPI_ErrorCallback(CMOCK_HAL_SPI_ErrorCallback_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi)
{
    cmock_call_instance->Expected_hspi = hspi;
}

void HAL_SPI_ErrorCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_ErrorCallback_CALL_INSTANCE));
    CMOCK_HAL_SPI_ErrorCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_ErrorCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_ErrorCallback_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_ErrorCallback_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_ErrorCallback(cmock_call_instance, hspi);
}

void HAL_SPI_AbortCpltCallback(SPI_HandleTypeDef* hspi)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_AbortCpltCallback_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_AbortCpltCallback);
    cmock_call_instance = (CMOCK_HAL_SPI_AbortCpltCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_AbortCpltCallback_CallInstance);
    Mock.HAL_SPI_AbortCpltCallback_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_AbortCpltCallback_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_AbortCpltCallback, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_SPI_AbortCpltCallback(CMOCK_HAL_SPI_AbortCpltCallback_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi)
{
    cmock_call_instance->Expected_hspi = hspi;
}

void HAL_SPI_AbortCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_AbortCpltCallback_CALL_INSTANCE));
    CMOCK_HAL_SPI_AbortCpltCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_AbortCpltCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_AbortCpltCallback_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_AbortCpltCallback_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_AbortCpltCallback(cmock_call_instance, hspi);
}

HAL_SPI_StateTypeDef HAL_SPI_GetState(SPI_HandleTypeDef* hspi)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_GetState_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_GetState);
    cmock_call_instance = (CMOCK_HAL_SPI_GetState_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_GetState_CallInstance);
    Mock.HAL_SPI_GetState_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_GetState_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_GetState, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_SPI_GetState(CMOCK_HAL_SPI_GetState_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi)
{
    cmock_call_instance->Expected_hspi = hspi;
}

void HAL_SPI_GetState_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, HAL_SPI_StateTypeDef cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_GetState_CALL_INSTANCE));
    CMOCK_HAL_SPI_GetState_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_GetState_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_GetState_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_GetState_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_GetState(cmock_call_instance, hspi);
    memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
           sizeof(HAL_SPI_StateTypeDef[sizeof(cmock_to_return) == sizeof(HAL_SPI_StateTypeDef) ? 1 : -1])); /* add HAL_SPI_StateTypeDef to :treat_as_array if this causes an error */
}

uint32_t HAL_SPI_GetError(SPI_HandleTypeDef* hspi)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_HAL_SPI_GetError_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_HAL_SPI_GetError);
    cmock_call_instance = (CMOCK_HAL_SPI_GetError_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SPI_GetError_CallInstance);
    Mock.HAL_SPI_GetError_CallInstance = CMock_Guts_MemNext(Mock.HAL_SPI_GetError_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_HAL_SPI_GetError, CMockString_hspi);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hspi), (void*)(hspi), sizeof(SPI_HandleTypeDef), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_SPI_GetError(CMOCK_HAL_SPI_GetError_CALL_INSTANCE* cmock_call_instance, SPI_HandleTypeDef* hspi)
{
    cmock_call_instance->Expected_hspi = hspi;
}

void HAL_SPI_GetError_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, uint32_t cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SPI_GetError_CALL_INSTANCE));
    CMOCK_HAL_SPI_GetError_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SPI_GetError_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.HAL_SPI_GetError_CallInstance = CMock_Guts_MemChain(Mock.HAL_SPI_GetError_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_HAL_SPI_GetError(cmock_call_instance, hspi);
    cmock_call_instance->ReturnVal = cmock_to_return;
}

