/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "MockCheckContactorError.h"

static const char* CMockString_contactorSense = "contactorSense";
static const char* CMockString_contactorState = "contactorState";
static const char* CMockString_isContactorError = "isContactorError";

typedef struct _CMOCK_isContactorError_CALL_INSTANCE
{
    UNITY_LINE_TYPE LineNumber;
    uint8_t ReturnVal;
    uint8_t Expected_contactorSense;
    ContactorState Expected_contactorState;

} CMOCK_isContactorError_CALL_INSTANCE;

static struct MockCheckContactorErrorInstance
{
    CMOCK_MEM_INDEX_TYPE isContactorError_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockCheckContactorError_Verify(void)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_MEM_INDEX_TYPE call_instance;
    call_instance = Mock.isContactorError_CallInstance;

    if (CMOCK_GUTS_NONE != call_instance)
    {
        UNITY_SET_DETAIL(CMockString_isContactorError);
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
    }
}

void MockCheckContactorError_Init(void)
{
    MockCheckContactorError_Destroy();
}

void MockCheckContactorError_Destroy(void)
{
    CMock_Guts_MemFreeAll();
    memset(&Mock, 0, sizeof(Mock));
}

uint8_t isContactorError(uint8_t contactorSense, ContactorState contactorState)
{
    UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
    CMOCK_isContactorError_CALL_INSTANCE* cmock_call_instance;
    UNITY_SET_DETAIL(CMockString_isContactorError);
    cmock_call_instance = (CMOCK_isContactorError_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.isContactorError_CallInstance);
    Mock.isContactorError_CallInstance = CMock_Guts_MemNext(Mock.isContactorError_CallInstance);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
    cmock_line = cmock_call_instance->LineNumber;
    {
        UNITY_SET_DETAILS(CMockString_isContactorError, CMockString_contactorSense);
        UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_contactorSense, contactorSense, cmock_line, CMockStringMismatch);
    }
    {
        UNITY_SET_DETAILS(CMockString_isContactorError, CMockString_contactorState);
        UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_contactorState), (void*)(&contactorState), sizeof(ContactorState), cmock_line, CMockStringMismatch);
    }
    UNITY_CLR_DETAILS();
    return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_isContactorError(CMOCK_isContactorError_CALL_INSTANCE* cmock_call_instance, uint8_t contactorSense, ContactorState contactorState)
{
    cmock_call_instance->Expected_contactorSense = contactorSense;
    memcpy((void*)(&cmock_call_instance->Expected_contactorState), (void*)(&contactorState),
           sizeof(ContactorState[sizeof(contactorState) == sizeof(ContactorState) ? 1 : -1])); /* add ContactorState to :treat_as_array if this causes an error */
}

void isContactorError_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t contactorSense, ContactorState contactorState, uint8_t cmock_to_return)
{
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_isContactorError_CALL_INSTANCE));
    CMOCK_isContactorError_CALL_INSTANCE* cmock_call_instance = (CMOCK_isContactorError_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
    memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
    Mock.isContactorError_CallInstance = CMock_Guts_MemChain(Mock.isContactorError_CallInstance, cmock_guts_index);
    cmock_call_instance->LineNumber = cmock_line;
    CMockExpectParameters_isContactorError(cmock_call_instance, contactorSense, contactorState);
    cmock_call_instance->ReturnVal = cmock_to_return;
}

