= Compiling and Flashing STM Board

NOTE: This has only been tested on Linux Mint, but is expected to work on other Debian based distros as well.

== Setup

. Navigate to STM32F4Discovery-Resources and run the auto installer using `sudo ./install.sh`. 
This should download STLink, gcc4mbed, and CubeMX2Makefile and add them all to the path.

. http://www.st.com/en/development-tools/stm32cubemx.html[Go to the download page of the official ST website by clicking this link^].

. Scroll to the bottom of the page to the *GET SOFTWARE* section and click *Get Software*.

. Follow the instructions and download CubeMX.

. Extract files from `.zip` file using a preferred method.
For example, use `unzip file.zip`.

. Navigate to the directory the files were extracted to.

. Run *SetupSTM32CubeMX-VERSION.linux* using `./SetupSTM32CubeMX-{var}.linux` where  {var} is the version of CubeMx that is being installed.

. Follow the instructions in the Installation Wizard.


== Generating Code with CubeMX

Note: If you are working on a project that already has the board configured, then this section can be skipped.

. Open CubeMX. The default path is `~/STM32CubeMX`.

. Select New Project.

. Click on the Board Selector Tab and scroll to STM32F4DISCOVERY then click OK.

. Go to Project > Settings.

. Name the project, set the project location, and change the Toolchain/IDE to SW4STM32. 
*If this isn't done, CubeMX2Makefile won't work!* 
CubeMX2Makefile looks for an SW4STM32 project which was created by CubeMX.
If the Toolchain/IDE is not set to SW4STM32, it will be in the format of a different IDE, not CubeMX.
For example, EWARM is for the IAR Embedded Workbench IDE and CubeMX2Makefile will not know what to do with that format.

. Make note of the Toolchain Folder Location, which will also be the project folder location.

. Click OK and download any dependencies that are needed, then click OK again.

. Make pin assignments then go to Project > Generate Code, and then save project.


== Generating a Makefile and Compiling

. Create the makefile using  `CubeMX2Makefile /path/to/project/folder`.

. Go to the directory that the Makefile was made then compile using `make`.

. Navigate to the build directory and there should be a `<project>.bin` & a `<project>.elf` file. Where `<project>` is the project name. 

== Flashing

Flashing is how the `.bin` or `.elf` that was made is put onto the board. 
This is how the processor on the board is able to carry out the instructions that were generated from the code.

There are two methods of flashing the boards - using the ST-Link Programmer, or using the Black Magic Probe

=== ST-Link Programmer

Connect the programmer to the board.

Flash the board using `st-flash write /path/to/project/build/<project>.bin 0x8000000`.

If a board isn't connected, and it ran successfully, the output should be: 
----
st-flash 1.3.0-dev
DATE/TIME WARN /opt/stlink/src/usb.c: Couldn't find any ST-Link/V2 devices
----

=== Black Magic Probe

The Black Magic Probe is compatible with both the 10-Pin & 20-Pin JTag headers. 
It also allows for debugging using GDB.

To load the `.elf` file onto the board, enter the `build/` directory.

. Plug in the Probe to the board and into your computer.
Determine where the probe is located on your computer, usually `/dev/ttyACM<X>`, where `<X>` is a number.
It can be located with `ls /dev/tty*`.
Typically, there are two devices listed there. 
Make note of the lowest value number.

. Use the command  `sudo arm-none-eabi-gdb <project>.elf`

. Scan for the probe with `target extended-remote /dev/ttyACM<X>`, using the value earlier.

. Use `monitor swdp_scan`.
If the device is not powered on, this will return nothing. 
In that case use `monitor tpwr enable`, and scan again.

. Attach the process with `attach <Y>`, <Y> being the output value from `swdp_scan` - typically 1.

. Load the program into the board. `load`

. Breakpoints can be set to help debug any potential issues. See the https://www.gnu.org/software/gdb/documentation/[official gdb guide] for more useful commands.


Alternatively, this can be done in one command by attaching mulitple `-ex` flags to the `arm-none-eabi-gdb` command:

```
 sudo arm-none-eabi-gdb EpsilonCCS.elf -ex 'target extended-remote /dev/ttyACM0' -ex 'monitor tpwr enable' -ex 'monitor swdp_scan' -ex 'attach 1' -ex 'load'
 
```
Or, there is a new script that does the above:
In the root directory, run

```
./gdbflash.sh -p /path/to/project -b /path/to/blackmagic
```
